import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export const supportedLanguages = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'mr', label: 'मराठी' },
  { code: 'gu', label: 'ગુજરાતી' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'te', label: 'తెలుగు' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'kn', label: 'ಕನ್ನಡ' },
  { code: 'ml', label: 'മലയാളം' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ' },
  { code: 'or', label: 'ଓଡ଼ିଆ' },
  { code: 'ur', label: 'اردو' },
  { code: 'bho', label: 'भोजपुरी' },
  { code: 'mai', label: 'मैथिली' },
  { code: 'chh', label: 'छत्तीसगढ़ी' },
  { code: 'sa', label: 'संस्कृत' }
];

const baseEnglish = {
  badge: 'Next-Gen Municipal Tech',
  title: 'Smart Water Complaint Management System',
  subtitle: 'Report water supply problems in seconds, track real-time resolution timelines, and help authorities build smarter, leakage-free cities.',
  reportComplaint: 'Report Complaint',
  trackComplaint: 'Track Complaint',
  serviceDesk: 'Service desk online',
  reportIssue: 'Report an issue',
  home: 'Home',
  report: 'Report complaint',
  track: 'Track status',
  analytics: 'Analytics',
  comparison: 'Comparison',
  blog: 'News and blog',
  rewards: 'Civic rewards',
  operations: 'Operations',
  dashboard: 'Dashboard',
  bookService: 'Book a service',
  payments: 'Payments',
  profile: 'Profile',
  loginRegister: 'Login or register',
  navigateTitle: 'Navigate JalSahay',
  languageLabel: 'Language',
  chooseLanguage: 'Choose language',
  languageNote: 'Select the language you prefer for the app.',
  menu: 'Menu',
  viewProfile: 'View profile',
  accessPortal: 'Access portal',
  chooseAccountType: 'Choose your account type',
  customerLogin: 'Customer login',
  customerAccess: 'Customer access',
  customerDescription: 'Book water services, report problems, track jobs, and pay directly from the app.',
  authorityLogin: 'Authority login',
  authorityAccess: 'Authority access',
  authorityDescription: 'Receive service requests, manage assignments, monitor jobs, and receive settlements for completed work.',
  login: 'Login',
  register: 'Register',
  signIn: 'Sign In',
  signInGoogle: 'Sign In with Google',
  needAccount: 'Need an account?',
  email: 'Email',
  password: 'Password',
  fullName: 'Full Name',
  enterFullName: 'Enter your full name',
  authorityOrg: 'Authority / Organization',
  waterDept: 'Municipal water department',
  registerAs: 'Register as',
  customer: 'Customer',
  authority: 'Authority',
  authorityRegistration: 'Authority registration',
  customerRegistration: 'Customer registration',
  createJalSahayAccount: 'Create JalSahay Account',
  alreadyRegistered: 'Already registered?',
  trackComplaintStatus: 'Track Complaint Status',
  complaintIdPhone: 'Enter your Complaint ID or Registered Phone Number',
  search: 'Search',
  enterComplaintIdPhone: 'Enter Complaint ID or Phone...',
  searching: 'Searching...',
  noComplaintRecords: 'No complaint records found.',
  assignedEngineer: 'Assigned Engineer:',
  estimatedResolution: 'Estimated Resolution:',
  addressLocation: 'Address Location:',
  notAssignedYet: 'Not assigned yet',
  notAvailableYet: 'Not available yet',
  reportWaterComplaint: 'Report a Water Complaint',
  fillAccurateDetails: 'Fill in accurate details for quick municipal dispatch.',
  complaintSubmitted: 'Complaint Submitted Successfully!',
  complaintSaved: 'Your complaint has been saved successfully.',
  complaintReferenceId: 'Complaint Reference ID',
  useReferenceId: 'You can use this reference ID to track your complaint.',
  fileAnotherComplaint: 'File Another Complaint',
  phoneNumber: 'Phone Number',
  category: 'Category',
  priorityLevel: 'Priority Level',
  wardNumber: 'Ward Number',
  specificAddress: 'Specific Address / Landmark',
  descriptionOfIssue: 'Description of Issue',
  uploadPhotos: 'Upload Photos',
  attachVideo: 'Attach Video (Optional)',
  submitMunicipalTicket: 'Submit Municipal Ticket',
  submittingComplaint: 'Submitting Complaint...',
  pipelineLeakage: 'Pipeline Leakage',
  noWaterSupply: 'No Water Supply',
  dirtyWater: 'Dirty Water',
  lowPressure: 'Low Pressure',
  waterWastage: 'Water Wastage',
  illegalConnection: 'Illegal Connection',
  low: 'Low',
  medium: 'Medium',
  high: 'High',
  emergency: 'Emergency',
  gpsNotSupported: 'GPS is not supported by this browser.',
  locationPermissionDenied: 'Location permission denied. You can enter the address manually.',
  loginBeforeComplaint: 'Please login before submitting a complaint.',
  complaintSubmissionFailed: 'Complaint submission failed:',
  somethingWentWrong: 'Something went wrong while submitting the complaint.',
  gpsCoordinatesNotLocked: 'GPS Coordinates not locked',
  detectGpsLocation: 'Detect GPS Location',
  authorityPortal: 'Authority portal',
  operationsDashboard: 'Operations dashboard',
  activeJobs: 'Active jobs',
  assignedTeams: 'Assigned teams',
  bookedValue: 'Booked value',
  requests: 'Requests',
  incomingServiceRequests: 'Incoming service requests',
  noLiveServiceRequests: 'No live service requests are waiting.',
  acceptRequest: 'Accept request',
  startJob: 'Start job',
  markCompleted: 'Mark completed',
  priorityAlerts: 'Priority alerts',
  settlementSummary: 'Settlement summary',
  completedJobs: 'Completed jobs',
  pendingPayout: 'Pending payout',
  platformCommission: 'Platform commission',
  bookWaterService: 'Book a water service',
  serviceRequestBooked: 'Service request booked',
  requestSent: 'Your request has been sent to the nearest authority partner.',
  service: 'Service',
  eta: 'ETA',
  amount: 'Amount',
  payment: 'Payment',
  location: 'Location',
  pendingConfirmation: 'Pending confirmation',
  chooseService: 'Choose a service',
  bookingDetails: 'Booking details',
  serviceAddress: 'Service address',
  enterFullServiceLocation: 'Enter full service location',
  preferredArrivalWindow: 'Preferred arrival window',
  paymentMethod: 'Payment method',
  serviceFee: 'Service fee',
  platformFee: 'Platform fee',
  total: 'Total',
  payAndConfirm: 'Pay & confirm booking',
  customerWallet: 'Customer wallet',
  paymentsAndReceipts: 'Payments and receipts',
  everyBooking: 'Every booking payment is recorded here with its current settlement status.',
  recordedPayments: 'Recorded payments',
  noPaymentRecords: 'No payment records yet. Book a service to create the first receipt.',
  noComplaintsYet: "You haven't submitted any complaints yet.",
  loadingComplaints: 'Loading your complaints...',
  citizenId: 'Citizen ID',
  bookmarks: 'Bookmarks',
  notifications: 'Notifications',
  noBookmarks: 'No bookmarked complaints or municipal notices yet.',
  noNotifications: 'No notifications yet.',
  civicRewards: 'Civic Rewards',
  rewardingParticipation: 'Rewarding verified participation in the water network',
  rewardDescription: 'Earn civic points through verified reporting, tracking, and resolution updates. Points unlock practical benefits, including free inspections and service credits.',
  currentBalance: 'Current balance',
  civicPoints: 'Civic points',
  verifiedReports: 'Verified reports',
  resolvedFollowUps: 'Resolved follow-ups',
  nextBenefit: 'Next benefit',
  benefitTierActive: 'Benefit tier active',
  progressTowardBenefit: 'Progressing toward your first benefit',
  currentStatus: 'Current status',
  howPointsEarned: 'How points are earned',
  nextUnlockedBenefit: 'Next unlocked benefit',
  benefits: 'Benefits',
  citizenServiceRewards: 'Citizen service rewards',
  verifiedParticipationOnly: 'Verified participation only',
  programPolicy: 'Program policy',
  eligibility: 'Eligibility based on verified community engagement',
  serviceSupportManaged: 'Service support managed by municipal operations',
  active: 'Active',
  locked: 'Locked',
  quickLinks: 'Quick Links',
  fileComplaint: 'File Complaint',
  trackGrievance: 'Track Grievance',
  cityAnalytics: 'City Analytics',
  toolComparison: 'Tool Comparison',
  categories: 'Categories',
  emergencyHelpline: 'Emergency Helpline',
  builtForSmartCities: 'Built for Smart Cities.',
  summary: 'Summary',
  submitted: 'Submitted',
  assigned: 'Assigned',
  inProgress: 'In Progress',
  resolved: 'Resolved',
  closed: 'Closed',
  status: 'Status',
  priority: 'Priority',
  address: 'Address',
  details: 'Details',
  save: 'Save',
  cancel: 'Cancel',
  update: 'Update',
  keyPlatformFeatures: 'Key Platform Features',
  featureDescription: 'Designed for extreme speed, transparency, and municipal efficiency.',
  realTimeTracking: 'Real-time Tracking',
  proof: 'Photo & Video Proof',
  gpsPrecision: 'GPS Precision',
  authorityDashboardFeature: 'Authority Dashboard',
  emergencySosMode: 'Emergency SOS Mode',
  waterAnalytics: 'Water Analytics',
  howJalSahayWorks: 'How JalSahay Works',
  loginRegisterStep: 'Login / Register',
  submitIssueStep: 'Submit Issue',
  authorityReviewStep: 'Authority Review',
  issueResolvedStep: 'Issue Resolved',
  step01: '01',
  step02: '02',
  step03: '03',
  step04: '04',
  overview: 'Overview and updates',
  reportComplaintDescription: 'Submit a water issue',
  trackStatusDescription: 'Follow a submitted issue',
  analyticsDescription: 'Service and area insights',
  comparisonDescription: 'Compare service performance',
  blogDescription: 'Water network updates',
  rewardsDescription: 'Your verified participation',
  operationsDescription: 'Manage authority requests',
  dashboardDescription: 'Your service overview',
  bookServiceDescription: 'Request water support',
  paymentsDescription: 'Receipts and history',
  profileDescription: 'Your profile',
  support: 'Support',
  description: 'Description',
  backToHome: 'Back to Home',
  loading: 'Loading',
  servicePartner: 'Nearest authority partner',
  user: 'User',
  citizenIdLabel: 'Citizen ID',
  complaintsTab: 'Complaints',
  bookmarksTab: 'Bookmarks',
  notificationsTab: 'Notifications',
  priorityLabel: 'Priority',
  loadingYourComplaints: 'Loading your complaints...',
  noComplaintsSubmitted: "You haven't submitted any complaints yet.",
  noBookmarkedNotices: 'No bookmarked complaints or municipal notices yet.',
  noNotificationsYet: 'No notifications yet.',
  customerService: 'Customer service',
  unableCreateRequest: 'Unable to create the service request.',
  requestSentAuthority: 'Your request has been sent to the nearest authority partner.',
  payConfirmBooking: 'Pay & confirm booking',
  adminPanel: 'Municipal Authority Admin Panel',
  manageComplaints: 'Manage incoming complaints and update their status.',
  noComplaintsSubmittedYet: 'No complaints have been submitted yet.',
  citizen: 'Citizen',
  ward: 'Ward',
  action: 'Action',
  couldNotUpdateStatus: 'Could not update status:',
  noServiceRiskData: 'No service risk data available.',
  waterServiceRiskMap: 'Water Service Risk Map',
  weatherComplaintRisk: 'Weather and complaint activity based risk analysis',
  riskScore: 'Risk Score',
  nearbyComplaints: 'Nearby complaints',
  openComplaints: 'Open complaints',
  highPriorityLabel: 'High priority',
  temperature: 'Temperature',
  humidity: 'Humidity',
  sevenDayRainfall: '7-day rainfall',
  maximumWind: 'Maximum wind',
  maximumTemperature: 'Maximum temperature',
  critical: 'Critical',
  toggleTheme: 'Toggle theme',
  pageNotFound: 'Page Not Found',
  loginFailed: 'Login failed. Please try again.',
  accountRegistered: 'Account registered successfully!',
  unableLoadRequests: 'Unable to load service requests.',
  unableUpdateRequest: 'Unable to update this request.',
  customerId: 'Customer ID',
  mainLineBurst: 'Main line burst',
  requestsAwaitingDispatch: 'high-priority requests awaiting dispatch',
  pressureDropReported: 'Pressure drop reported',
  westernCorridorIssue: 'Water supply issue in western corridor',
  waterQualityCheckPending: 'Water quality check pending',
  sampleReviewDue: 'Sample review due by 8 PM',
  yourLocation: 'Your current GPS location',
  activeStatus: 'Active',
  lockedStatus: 'Locked',
  eligibilityText: 'Eligibility based on verified community engagement',
  serviceSupportText: 'Service support managed by municipal operations',
  waterServiceNetwork: 'Water service network',
  connectReportResolve: 'Connect, report, and resolve with confidence.',
  closeNavigation: 'Close navigation',
  openProfile: 'Open profile',
  authorityAccount: 'Authority account',
  customerAccount: 'Customer account',
  yourWorkspace: 'Your workspace',
  exploreJalSahay: 'Explore JalSahay',
  signOut: 'Sign out',
  traditionalVsJalSahay: 'Traditional System vs. JalSahay',
  whyModernCities: 'Why modern cities are upgrading to automated water portal management.',
  feature: 'Feature',
  traditionalSystem: 'Traditional System',
  jalsahaySmartSystem: 'JalSahay Smart System',
  waterConservationNews: 'Water Conservation & Municipal News',
  articlesGuidelines: 'Articles and guidelines on smart water management.',
  by: 'By',
  rewardingVerifiedParticipation: 'Rewarding verified participation in the water network',
  pointEarning: 'Point earning',
  eligible: 'Eligible',
  inProgressLabel: 'In progress',
  progressTo: 'Progress to',
  basicInspectionCredit: 'Basic Inspection Credit',
  freeLeakInspection: 'Free leak inspection or basic service assessment.',
  complimentaryVisit: 'Complimentary visit',
  priorityServiceSupport: 'Priority Service Support',
  priorityScheduling: 'Priority scheduling for repair and maintenance support.',
  fastTrackService: 'Fast-track service',
  quarterlyWaterCheck: 'Quarterly Water Check',
  freeWaterQuality: 'One free water quality and pressure evaluation per quarter.',
  freeUtilityCheck: 'Free utility check',
  annualCivicCredit: 'Annual Civic Credit',
  waivedServiceFee: 'Waived service fee or one full utility assistance package.',
  freeServiceBundle: 'Free service bundle',
  submitVerifiedComplaint: 'Submit a verified complaint',
  requiredForReporting: 'Required for water leak, pressure, or contamination reporting.',
  trackComplaintProgress: 'Track complaint progress',
  helpsTransparency: 'Helps maintain transparency and follow-up completion.',
  successfulResolutionUpdate: 'Provide a successful resolution update',
  rewardsFixConfirmation: 'Rewards users who confirm a fix or closure.',
  repeatedQualityReporting: 'Repeated quality reporting',
  sustainedCivicEngagement: 'For sustained civic engagement in problem reporting.'
  ,onlineStatusTracking: 'Online Status Tracking'
  ,photoVideoUpload: 'Photo & Video Upload'
  ,exactGpsGeotagging: 'Exact GPS Geotagging'
  ,realTimePushAlerts: 'Real-time Push Alerts'
  ,wardAnalytics: 'Ward Analytics'
  ,avgResponseTime: 'Average Response Time'
  ,liveMunicipalOperations: 'LIVE MUNICIPAL OPERATIONS'
  ,waterIntelligenceDashboard: 'Water Intelligence Dashboard'
  ,realComplaintWeather: 'Real complaint data + live weather intelligence'
  ,refreshData: 'Refresh Data'
  ,highestAttentionRequired: 'Highest attention required'
  ,priorityScore: 'Priority score'
  ,totalComplaints: 'Total Complaints'
  ,open: 'Open'
  ,emergencyLabel: 'Emergency'
  ,highPriority: 'High Priority'
  ,criticalZones: 'Critical Zones'
  ,immediateMonitoring: 'Immediate monitoring recommended'
  ,highRiskZones: 'High Risk Zones'
  ,increasedAttention: 'Increased service attention required'
  ,monitoredZones: 'Monitored Zones'
  ,weatherComplaintAreas: 'Weather + complaint monitoring areas'
  ,complaintsByCategory: 'Complaints by Category'
  ,complaintsByWard: 'Complaints by Ward'
  ,complaintStatus: 'Complaint Status'
  ,serviceRiskAnalysis: 'Service Risk Analysis'
  ,zone: 'Zone'
  ,risk: 'Risk'
  ,score: 'Score'
  ,complaints: 'Complaints'
  ,rain: 'Rain'
  ,rainProbability: 'Rain Probability'
  ,immediateInspection: 'Immediate inspection'
  ,increaseMonitoring: 'Increase monitoring'
  ,monitor: 'Monitor'
  ,normalOperations: 'Normal operations'
  ,riskScoreNote: 'Risk scores are decision-support indicators calculated from live weather forecasts and complaint activity. They are not guaranteed predictions of incidents.'
  ,submittedCount: 'Submitted'
  ,pendingCount: 'Pending'
  ,averageResponseTime: 'Avg. response time'
  ,satisfaction: 'Satisfaction'
  ,realTimeTrackingDesc: 'Track exact stages from assignment to repair crew arrival.'
  ,photoVideoProofDesc: 'Attach geo-tagged media evidence for quick verification.'
  ,gpsPrecisionDesc: 'Pinpoint exact water leak locations down to precise coordinates.'
  ,authorityDashboardDesc: 'Engineers receive instant ward updates for dispatch.'
  ,emergencySosDesc: 'High priority flags for major pipe breaks and contaminated supply.'
  ,waterAnalyticsDesc: 'Data insights on repeat outage areas and ward performance.'
  ,loginRegisterDesc: 'Sign up via Google or email in seconds.'
  ,submitIssueDesc: 'Select category, snap a photo, and set GPS.'
  ,authorityReviewDesc: 'Ward engineer gets assigned instantly.'
  ,issueResolvedDesc: 'Receive real-time fix status and rate work.'
  ,userProfileSettings: 'User Profile Settings'
  ,registeredWard: 'Registered Ward'
  ,detectYourLocationFirst: 'Detect your location first.'
  ,yourComplaintLocation: 'Your complaint location'
  ,liveComplaintMap: 'Live Complaint Map'
  ,complaintLocationsSupabase: 'Complaint locations from Supabase'
  ,useMyGps: 'Use My GPS'
  ,locationPermissionMap: 'Location permission was denied. Please allow location access.'
  ,blog1Title: '10 Proven Ways to Save Water at Home'
  ,blog1Category: 'Water Conservation'
  ,blog1Summary: 'Simple daily changes can reduce household water consumption and prevent unnecessary wastage.'
  ,blog2Title: 'How to Report a Water Supply Problem'
  ,blog2Category: 'Citizen Services'
  ,blog2Summary: 'Learn how citizens can report leakage, dirty water, low pressure and water supply problems.'
  ,blog3Title: 'Why Water Leakage Needs Immediate Attention'
  ,blog3Category: 'Water Infrastructure'
  ,blog3Summary: 'Small leaks can become major infrastructure problems and waste large amounts of treated water.'
  ,blog4Title: 'Weather and Water Supply Management'
  ,blog4Category: 'Smart Water Management'
  ,blog4Summary: 'Weather information can help municipal teams prepare for heavy rainfall, flooding, water contamination and supply stress.'
};

const hindi = {
  ...baseEnglish,
  badge: 'अग्रणी नगरपालिका प्रौद्योगिकी',
  title: 'स्मार्ट जल शिकायत प्रबंधन प्रणाली',
  subtitle: 'कुछ सेकंड में जल आपूर्ति की समस्याएँ रिपोर्ट करें, वास्तविक समय में समाधान का ट्रैक रखें और अधिकारियों की मदद से स्मार्ट, रिसाव मुक्त शहर बनाएं।',
  reportComplaint: 'शिकायत दर्ज करें',
  trackComplaint: 'शिकायत ट्रैक करें',
  serviceDesk: 'सेवा डेस्क ऑनलाइन',
  reportIssue: 'समस्या रिपोर्ट करें',
  home: 'होम',
  report: 'शिकायत रिपोर्ट',
  track: 'स्थिति ट्रैक करें',
  analytics: 'विश्लेषण',
  comparison: 'तुलना',
  blog: 'समाचार और ब्लॉग',
  rewards: 'नागरिक पुरस्कार',
  operations: 'कार्य',
  dashboard: 'डैशबोर्ड',
  bookService: 'सेवा बुक करें',
  payments: 'भुगतान',
  profile: 'प्रोफ़ाइल',
  loginRegister: 'लॉगिन या रजिस्टर',
  navigateTitle: 'जलसहाय नेविगेट करें',
  languageLabel: 'भाषा',
  chooseLanguage: 'भाषा चुनें',
  languageNote: 'ऐप के लिए अपनी पसंदीदा भाषा चुनें।',
  menu: 'मेन्यू',
  viewProfile: 'प्रोफ़ाइल देखें',
  accessPortal: 'ऐक्सेस पोर्टल',
  chooseAccountType: 'अपना अकाउंट चुनें',
  customerLogin: 'ग्राहक लॉगिन',
  customerAccess: 'ग्राहक एक्सेस',
  customerDescription: 'पानी की सेवा बुक करें, समस्या रिपोर्ट करें, काम ट्रैक करें और ऐप से सीधे भुगतान करें।',
  authorityLogin: 'अधिकारी लॉगिन',
  authorityAccess: 'अधिकारी एक्सेस',
  authorityDescription: 'सेवा अनुरोध प्राप्त करें, कार्य आवंटन प्रबंधित करें, काम की स्थिति देखें और पूरा हुआ काम भुगतान प्राप्त करें।',
  login: 'लॉगिन',
  register: 'रजिस्टर',
  signIn: 'साइन इन',
  signInGoogle: 'Google से साइन इन',
  needAccount: 'अकाउंट चाहिए?',
  email: 'ईमेल',
  password: 'पासवर्ड',
  fullName: 'पूरा नाम',
  enterFullName: 'अपना पूरा नाम लिखें',
  authorityOrg: 'अधिकारी / संगठन',
  waterDept: 'नगरपालिका जल विभाग',
  registerAs: 'के रूप में रजिस्टर',
  customer: 'ग्राहक',
  authority: 'अधिकारी',
  authorityRegistration: 'अधिकारी पंजीकरण',
  customerRegistration: 'ग्राहक पंजीकरण',
  createJalSahayAccount: 'जलसहाय अकाउंट बनाएं',
  alreadyRegistered: 'पहले से रजिस्टर हैं?',
  trackComplaintStatus: 'शिकायत स्थिति ट्रैक करें',
  complaintIdPhone: 'अपना शिकायत आईडी या पंजीकृत फोन नंबर लिखें',
  search: 'खोजें',
  enterComplaintIdPhone: 'शिकायत आईडी या फोन लिखें...',
  searching: 'खोजा जा रहा है...',
  noComplaintRecords: 'कोई शिकायत रिकॉर्ड नहीं मिला।',
  assignedEngineer: 'नियुक्त इंजीनियर:',
  estimatedResolution: 'अनुमानित समाधान:',
  addressLocation: 'पता स्थान:',
  notAssignedYet: 'अभी तक नियुक्त नहीं',
  notAvailableYet: 'अभी उपलब्ध नहीं',
  reportWaterComplaint: 'जल शिकायत दर्ज करें',
  fillAccurateDetails: 'त्वरित नगरपालिका कार्य के लिए सही जानकारी भरें।',
  complaintSubmitted: 'शिकायत सफलतापूर्वक दर्ज हो गई!',
  complaintSaved: 'आपकी शिकायत सफलतापूर्वक सेव हो गई है।',
  complaintReferenceId: 'शिकायत संदर्भ आईडी',
  useReferenceId: 'इस संदर्भ आईडी का उपयोग करके आप अपनी शिकायत ट्रैक कर सकते हैं।',
  fileAnotherComplaint: 'अलग शिकायत दर्ज करें',
  phoneNumber: 'फोन नंबर',
  category: 'श्रेणी',
  priorityLevel: 'प्राथमिकता स्तर',
  wardNumber: 'वार्ड नंबर',
  specificAddress: 'सटीक पता / landmark',
  descriptionOfIssue: 'समस्या का विवरण',
  uploadPhotos: 'फोटो अपलोड करें',
  attachVideo: 'वीडियो जोड़ें (वैकल्पिक)',
  submitMunicipalTicket: 'नगरपालिका टिकट जमा करें',
  submittingComplaint: 'शिकायत जमा हो रही है...',
  pipelineLeakage: 'पाइपलाइन लीक',
  noWaterSupply: 'पानी की कमी',
  dirtyWater: 'गंदा पानी',
  lowPressure: 'कम दबाव',
  waterWastage: 'पानी की बर्बादी',
  illegalConnection: 'अवैध कनेक्शन',
  low: 'कम',
  medium: 'मध्यम',
  high: 'उच्च',
  emergency: 'आपातकाल',
  gpsNotSupported: 'इस ब्राउज़र में GPS समर्थित नहीं है।',
  locationPermissionDenied: 'स्थान की अनुमति नहीं दी गई। आप पता मैन्युअल दर्ज कर सकते हैं।',
  loginBeforeComplaint: 'शिकायत दर्ज करने से पहले लॉगिन करें।',
  complaintSubmissionFailed: 'शिकायत दर्ज करने में विफल:',
  somethingWentWrong: 'शिकायत दर्ज करते समय कुछ गलत हुआ।',
  gpsCoordinatesNotLocked: 'GPS कोऑर्डिनेट लॉक नहीं किया गया',
  detectGpsLocation: 'GPS स्थान पता करें',
  activeJobs: 'सक्रिय काम',
  assignedTeams: 'नियुक्त टीम',
  bookedValue: 'बुक किया गया मूल्य',
  requests: 'अनुरोध',
  incomingServiceRequests: 'आने वाले सेवा अनुरोध',
  noLiveServiceRequests: 'कोई लाइव सेवा अनुरोध नहीं है।',
  acceptRequest: 'अनुरोध स्वीकार करें',
  startJob: 'काम शुरू करें',
  markCompleted: 'पूर्ण चिह्नित करें',
  priorityAlerts: 'प्राथमिकता अलर्ट',
  settlementSummary: 'सेटलमेंट सारांश',
  completedJobs: 'पूर्ण काम',
  pendingPayout: 'लंबित भुगतान',
  platformCommission: 'प्लेटफॉर्म कमीशन',
  customerService: 'ग्राहक सेवा',
  bookWaterService: 'पानी सेवा बुक करें',
  serviceRequestBooked: 'सेवा अनुरोध बुक हो गया',
  requestSent: 'आपका अनुरोध निकटतम अधिकारी साथी को भेज दिया गया है।',
  service: 'सेवा',
  eta: 'ETA',
  amount: 'राशि',
  payment: 'भुगतान',
  location: 'स्थान',
  pendingConfirmation: 'पुष्टि लंबित',
  chooseService: 'सेवा चुनें',
  bookingDetails: 'बुकिंग विवरण',
  serviceAddress: 'सेवा पता',
  enterFullServiceLocation: 'पूरा सेवा पता लिखें',
  preferredArrivalWindow: 'पसंदीदा आगमन समय',
  paymentMethod: 'भुगतान का तरीका',
  serviceFee: 'सेवा शुल्क',
  platformFee: 'प्लेटफॉर्म शुल्क',
  total: 'कुल',
  payAndConfirm: 'भुगतान करें और बुकिंग की पुष्टि करें',
  customerWallet: 'ग्राहक वॉलेट',
  paymentsAndReceipts: 'भुगतान और रसीदें',
  everyBooking: 'हर बुकिंग का भुगतान यहाँ दर्ज है, साथ में वर्तमान सेटलमेंट स्थिति भी है।',
  recordedPayments: 'रिकॉर्ड किए गए भुगतान',
  noPaymentRecords: 'अभी कोई भुगतान रिकार्ड नहीं है। सेवा बुक करें और पहली रसीद बनाएं।',
  noComplaintsYet: 'आपने अभी तक कोई शिकायत नहीं दर्ज की है।',
  loadingComplaints: 'आपकी शिकायतें लोड हो रही हैं...',
  citizenId: 'नागरिक आईडी',
  bookmarks: 'बुकमार्क',
  notifications: 'सूचनाएं',
  noBookmarks: 'अभी तक कोई बुकमार्क या नगरपालिक सूचना नहीं है।',
  noNotifications: 'अभी कोई सूचना नहीं है।',
  civicRewards: 'नागरिक पुरस्कार',
  rewardingParticipation: 'जल नेटवर्क में सत्यापित भागीदारी के लिए पुरस्कार',
  rewardDescription: 'सत्यापित रिपोर्टिंग, ट्रैकिंग और समाधान अपडेट के लिए नागरिक अंक कमाएँ। अंक मुफ्त निरीक्षण और सेवा क्रेडिट जैसी सुविधाएँ दे सकते हैं।',
  currentBalance: 'वर्तमान बैलेंस',
  civicPoints: 'नागरिक अंक',
  verifiedReports: 'सत्यापित रिपोर्ट',
  resolvedFollowUps: 'हल किए गए फॉलोअप',
  nextBenefit: 'अगला लाभ',
  benefitTierActive: 'लाभ स्तर सक्रिय',
  progressTowardBenefit: 'पहले लाभ की ओर प्रगति',
  currentStatus: 'वर्तमान स्थिति',
  howPointsEarned: 'अंक कैसे कमाए जाते हैं',
  nextUnlockedBenefit: 'अगला अनलॉक लाभ',
  benefits: 'लाभ',
  citizenServiceRewards: 'नागरिक सेवा पुरस्कार',
  verifiedParticipationOnly: 'केवल सत्यापित भागीदारी',
  programPolicy: 'प्रोग्राम नीति',
  eligibility: 'सत्यापित समुदाय सहभागिता के आधार पर पात्रता',
  serviceSupportManaged: 'सेवा सहायता नगरपालिका संचालन द्वारा प्रबंधित की जाती है',
  active: 'सक्रिय',
  locked: 'लॉक',
  quickLinks: 'त्वरित लिंक',
  fileComplaint: 'शिकायत दर्ज करें',
  trackGrievance: 'शिकायत ट्रैक करें',
  cityAnalytics: 'शहर विश्लेषण',
  toolComparison: 'टूल तुलना',
  categories: 'श्रेणियाँ',
  emergencyHelpline: 'आपातकालीन हेल्पलाइन',
  builtForSmartCities: 'स्मार्ट सिटी के लिए बनाया गया।',
  summary: 'सारांश',
  submitted: 'दर्ज किया गया',
  assigned: 'नियुक्त',
  inProgress: 'कार्य में',
  resolved: 'हल हो गया',
  closed: 'बंद',
  status: 'स्थिति',
  priority: 'प्राथमिकता',
  address: 'पता',
  details: 'विवरण',
  save: 'सेव',
  cancel: 'रद्द करें',
  update: 'अपडेट',
  keyPlatformFeatures: 'मुख्य प्लेटफॉर्म फीचर्स',
  featureDescription: 'अत्यधिक गति, पारदर्शिता और नगरपालिका दक्षता के लिए बनाया गया।',
  realTimeTracking: 'रियल-टाइम ट्रैकिंग',
  proof: 'फोटो और वीडियो प्रमाण',
  gpsPrecision: 'GPS सटीकता',
  authorityDashboardFeature: 'अधिकारी डैशबोर्ड',
  emergencySosMode: 'आपातकालीन SOS मोड',
  waterAnalytics: 'पानी विश्लेषण',
  howJalSahayWorks: 'जलसहाय कैसे काम करता है',
  loginRegisterStep: 'लॉगिन / रजिस्टर',
  submitIssueStep: 'समस्या दर्ज करें',
  authorityReviewStep: 'अधिकारी समीक्षा',
  issueResolvedStep: 'समस्या हल हुई',
  overview: 'सामग्री और अपडेट',
  reportComplaintDescription: 'पानी की समस्या दर्ज करें',
  trackStatusDescription: 'दर्ज की गई समस्या का ट्रैक रखें',
  analyticsDescription: 'सेवा और क्षेत्र की जानकारी',
  comparisonDescription: 'सेवा प्रदर्शन की तुलना करें',
  blogDescription: 'जल नेटवर्क अपडेट',
  rewardsDescription: 'आपकी सत्यापित भागीदारी',
  operationsDescription: 'अधिकारी अनुरोध प्रबंधन',
  dashboardDescription: 'आपकी सेवा अवलोकन',
  bookServiceDescription: 'पानी सहायता का अनुरोध करें',
  paymentsDescription: 'रसीदें और इतिहास',
  profileDescription: 'आपकी प्रोफ़ाइल',
  support: 'सहायता',
  description: 'विवरण',
  backToHome: 'होम पर वापस',
  loading: 'लोड हो रहा है',
  servicePartner: 'निकटतम अधिकारी साझेदार',
  user: 'उपयोगकर्ता',
  waterServiceNetwork: 'जल सेवा नेटवर्क',
  connectReportResolve: 'जुड़ें, शिकायत दर्ज करें और भरोसे के साथ समाधान पाएं।',
  authorityAccount: 'अधिकारी अकाउंट',
  customerAccount: 'ग्राहक अकाउंट',
  yourWorkspace: 'आपका कार्यक्षेत्र',
  exploreJalSahay: 'जलसहाय देखें',
  signOut: 'साइन आउट',
  authorityPortal: 'अधिकारी पोर्टल',
  operationsDashboard: 'कार्य डैशबोर्ड',
  rewardingVerifiedParticipation: 'जल नेटवर्क में सत्यापित भागीदारी के लिए पुरस्कार',
  pointEarning: 'अंक कैसे कमाएं',
  inProgressLabel: 'प्रगति में',
  progressTo: 'प्रगति:',
  onlineStatusTracking: 'ऑनलाइन स्थिति ट्रैकिंग',
  photoVideoUpload: 'फोटो और वीडियो अपलोड',
  exactGpsGeotagging: 'सटीक GPS जियोटैगिंग',
  realTimePushAlerts: 'रियल-टाइम पुश अलर्ट',
  wardAnalytics: 'वार्ड विश्लेषण',
  avgResponseTime: 'औसत प्रतिक्रिया समय',
  traditionalVsJalSahay: 'पारंपरिक प्रणाली बनाम जलसहाय',
  whyModernCities: 'आधुनिक शहर स्वचालित जल पोर्टल प्रबंधन क्यों अपना रहे हैं।',
  feature: 'सुविधा',
  traditionalSystem: 'पारंपरिक प्रणाली',
  jalsahaySmartSystem: 'जलसहाय स्मार्ट प्रणाली',
  waterConservationNews: 'जल संरक्षण और नगरपालिका समाचार',
  articlesGuidelines: 'स्मार्ट जल प्रबंधन पर लेख और दिशानिर्देश।',
  by: 'द्वारा',
  basicInspectionCredit: 'बेसिक निरीक्षण क्रेडिट',
  freeLeakInspection: 'मुफ्त रिसाव निरीक्षण या बेसिक सेवा मूल्यांकन।',
  complimentaryVisit: 'मुफ्त विजिट',
  priorityServiceSupport: 'प्राथमिकता सेवा सहायता',
  priorityScheduling: 'मरम्मत और रखरखाव सहायता के लिए प्राथमिकता शेड्यूलिंग।',
  fastTrackService: 'त्वरित सेवा',
  quarterlyWaterCheck: 'त्रैमासिक जल जांच',
  freeWaterQuality: 'हर तिमाही एक मुफ्त जल गुणवत्ता और दबाव मूल्यांकन।',
  freeUtilityCheck: 'मुफ्त उपयोगिता जांच',
  annualCivicCredit: 'वार्षिक नागरिक क्रेडिट',
  waivedServiceFee: 'सेवा शुल्क माफ या एक पूर्ण उपयोगिता सहायता पैकेज।',
  freeServiceBundle: 'मुफ्त सेवा पैकेज',
  submitVerifiedComplaint: 'सत्यापित शिकायत दर्ज करें',
  requiredForReporting: 'जल रिसाव, दबाव या प्रदूषण रिपोर्टिंग के लिए आवश्यक।',
  trackComplaintProgress: 'शिकायत की प्रगति ट्रैक करें',
  helpsTransparency: 'पारदर्शिता और फॉलो-अप पूरा करने में मदद करता है।',
  successfulResolutionUpdate: 'सफल समाधान अपडेट दें',
  rewardsFixConfirmation: 'समाधान या बंद होने की पुष्टि करने वाले उपयोगकर्ताओं को पुरस्कार।',
  repeatedQualityReporting: 'लगातार गुणवत्तापूर्ण रिपोर्टिंग',
  sustainedCivicEngagement: 'समस्या रिपोर्टिंग में निरंतर नागरिक भागीदारी के लिए।',
  liveMunicipalOperations: 'लाइव नगरपालिका संचालन',
  waterIntelligenceDashboard: 'जल जानकारी डैशबोर्ड',
  realComplaintWeather: 'वास्तविक शिकायत डेटा और लाइव मौसम जानकारी',
  refreshData: 'डेटा रीफ्रेश करें',
  highestAttentionRequired: 'सबसे अधिक ध्यान आवश्यक',
  priorityScore: 'प्राथमिकता स्कोर',
  totalComplaints: 'कुल शिकायतें',
  open: 'खुली',
  emergencyLabel: 'आपातकाल',
  highPriority: 'उच्च प्राथमिकता',
  criticalZones: 'गंभीर क्षेत्र',
  immediateMonitoring: 'तत्काल निगरानी की सलाह',
  highRiskZones: 'उच्च जोखिम वाले क्षेत्र',
  increasedAttention: 'अधिक सेवा ध्यान आवश्यक',
  monitoredZones: 'निगरानी वाले क्षेत्र',
  weatherComplaintAreas: 'मौसम और शिकायत निगरानी क्षेत्र',
  complaintsByCategory: 'श्रेणी के अनुसार शिकायतें',
  complaintsByWard: 'वार्ड के अनुसार शिकायतें',
  complaintStatus: 'शिकायत स्थिति',
  serviceRiskAnalysis: 'सेवा जोखिम विश्लेषण',
  zone: 'क्षेत्र',
  risk: 'जोखिम',
  score: 'स्कोर',
  complaints: 'शिकायतें',
  rain: 'बारिश',
  rainProbability: 'बारिश की संभावना',
  action: 'कार्यवाही',
  immediateInspection: 'तत्काल निरीक्षण',
  increaseMonitoring: 'निगरानी बढ़ाएं',
  monitor: 'निगरानी करें',
  normalOperations: 'सामान्य संचालन',
  riskScoreNote: 'जोखिम स्कोर लाइव मौसम पूर्वानुमान और शिकायत गतिविधि से निकाले गए निर्णय-सहायता संकेतक हैं। ये घटनाओं की गारंटीकृत भविष्यवाणी नहीं हैं।',
  submittedCount: 'दर्ज शिकायतें',
  pendingCount: 'लंबित',
  averageResponseTime: 'औसत प्रतिक्रिया समय',
  satisfaction: 'संतुष्टि',
  realTimeTrackingDesc: 'नियुक्ति से मरम्मत दल के पहुंचने तक हर चरण ट्रैक करें।',
  photoVideoProofDesc: 'त्वरित सत्यापन के लिए जियोटैग फोटो और वीडियो जोड़ें।',
  gpsPrecisionDesc: 'पानी के रिसाव का सटीक स्थान और निर्देशांक पता करें।',
  authorityDashboardDesc: 'इंजीनियरों को कार्यवाही के लिए वार्ड अपडेट तुरंत मिलते हैं।',
  emergencySosDesc: 'बड़ी पाइप टूटने और दूषित आपूर्ति के लिए उच्च प्राथमिकता अलर्ट।',
  waterAnalyticsDesc: 'बार-बार होने वाली समस्या और वार्ड प्रदर्शन की जानकारी।',
  loginRegisterDesc: 'Google या ईमेल से कुछ सेकंड में साइन अप करें।',
  submitIssueDesc: 'श्रेणी चुनें, फोटो लें और GPS सेट करें।',
  authorityReviewDesc: 'वार्ड इंजीनियर तुरंत नियुक्त किया जाता है।',
  issueResolvedDesc: 'रियल-टाइम समाधान स्थिति पाएं और काम को रेट करें।',
  userProfileSettings: 'उपयोगकर्ता प्रोफ़ाइल सेटिंग्स',
  registeredWard: 'पंजीकृत वार्ड',
  detectYourLocationFirst: 'पहले अपना स्थान पता करें।',
  yourComplaintLocation: 'आपकी शिकायत का स्थान',
  liveComplaintMap: 'लाइव शिकायत मानचित्र',
  complaintLocationsSupabase: 'Supabase से शिकायत स्थान',
  useMyGps: 'मेरा GPS उपयोग करें',
  locationPermissionMap: 'स्थान की अनुमति नहीं मिली। कृपया स्थान की अनुमति दें।',
  blog1Title: 'घर में पानी बचाने के 10 प्रमाणित तरीके',
  blog1Category: 'जल संरक्षण',
  blog1Summary: 'रोज़मर्रा के छोटे बदलाव घर में पानी की खपत और अनावश्यक बर्बादी कम कर सकते हैं।',
  blog2Title: 'जल आपूर्ति की समस्या कैसे रिपोर्ट करें',
  blog2Category: 'नागरिक सेवाएं',
  blog2Summary: 'जानें कि नागरिक रिसाव, गंदे पानी, कम दबाव और जल आपूर्ति की समस्याएं कैसे रिपोर्ट कर सकते हैं।',
  blog3Title: 'पानी के रिसाव पर तुरंत ध्यान क्यों जरूरी है',
  blog3Category: 'जल आधारभूत संरचना',
  blog3Summary: 'छोटे रिसाव बड़ी बुनियादी समस्याएं बन सकते हैं और बहुत सारा उपचारित पानी बर्बाद कर सकते हैं।',
  blog4Title: 'मौसम और जल आपूर्ति प्रबंधन',
  blog4Category: 'स्मार्ट जल प्रबंधन',
  blog4Summary: 'मौसम की जानकारी नगरपालिका टीमों को भारी बारिश, बाढ़, जल प्रदूषण और आपूर्ति दबाव के लिए तैयार कर सकती है।'
};

const marathi = {
  ...baseEnglish,
  badge: 'आधुनिक नगरपरिषदेची तंत्रज्ञान',
  title: 'स्मार्ट पाणी तक्रार व्यवस्थापन प्रणाली',
  subtitle: 'सेकंदात पाण्याशी संबंधित समस्या नोंदवा, रिअल टाइममध्ये निराकरण ट्रॅक करा आणि अधिक स्मार्ट, गळतीमुक्त शहर तयार करण्यात मदत करा.',
  reportComplaint: 'तक्रार नोंदवा',
  trackComplaint: 'तक्रार ट्रॅक करा',
  serviceDesk: 'सेवा डेस्क ऑनलाइन',
  reportIssue: 'समस्या नोंदवा',
  home: 'मुख्यपृष्ठ',
  report: 'तक्रार नोंदणी',
  track: 'स्थिती बघा',
  analytics: 'विश्लेषण',
  comparison: 'तुलना',
  blog: 'बातम्या आणि ब्लॉग',
  rewards: 'नागरिक बक्षिसे',
  operations: 'कार्यवाही',
  dashboard: 'डॅशबोर्ड',
  bookService: 'सेवा बुक करा',
  payments: 'देयके',
  profile: 'प्रोफाइल',
  loginRegister: 'लॉगिन किंवा नोंदणी',
  navigateTitle: 'जळसहाय नेव्हिगेट करा',
  languageLabel: 'भाषा',
  chooseLanguage: 'भाषा निवडा',
  languageNote: 'अ‍ॅपसाठी आपली आवडती भाषा निवडा.',
  menu: 'मेनू',
  viewProfile: 'प्रोफाइल पाहा',
  accessPortal: 'अ‍ॅक्सेस पोर्टल',
  chooseAccountType: 'आपला खातीचा प्रकार निवडा',
  customerLogin: 'ग्राहक लॉगिन',
  customerAccess: 'ग्राहक प्रवेश',
  customerDescription: 'पाणी सेवा बुक करा, समस्या नोंदवा, काम ट्रॅक करा आणि अ‍ॅपमधून थेट पेमेंट करा.',
  authorityLogin: 'प्राधिकरण लॉगिन',
  authorityAccess: 'प्राधिकरण प्रवेश',
  authorityDescription: 'सेवा विनंत्या प्राप्त करा, काम नियुक्त करा, काम पाहा आणि पूर्ण झाल्यावर देयके मिळवा.',
  login: 'लॉगिन',
  register: 'नोंदणी',
  signIn: 'साइन इन',
  signInGoogle: 'Google सह साइन इन',
  needAccount: 'खाते आवश्यक आहे?',
  email: 'ईमेल',
  password: 'पासवर्ड',
  fullName: 'पूर्ण नाव',
  enterFullName: 'आपले पूर्ण नाव भरा',
  authorityOrg: 'प्राधिकरण / संस्था',
  waterDept: 'नगरपालिका जल विभाग',
  registerAs: 'म्हणून नोंदणी करा',
  customer: 'ग्राहक',
  authority: 'प्राधिकरण',
  authorityRegistration: 'प्राधिकरण नोंदणी',
  customerRegistration: 'ग्राहक नोंदणी',
  createJalSahayAccount: 'जळसहाय खाते तयार करा',
  alreadyRegistered: 'आधीपासून नोंदणी केले आहे?',
  trackComplaintStatus: 'तक्रार स्थिती ट्रॅक करा',
  complaintIdPhone: 'तुमचा तक्रार आयडी किंवा नोंदणी केलेला फोन नंबर भरा',
  search: 'शोध',
  enterComplaintIdPhone: 'तक्रार आयडी किंवा फोन भरा...',
  searching: 'शोधत आहे...',
  noComplaintRecords: 'कोणताही तक्रार रेकॉर्ड सापडला नाही.',
  assignedEngineer: 'नियुक्त अभियंता:',
  estimatedResolution: 'अंदाजे निराकरण:',
  addressLocation: 'पत्ता / ठिकाण:',
  notAssignedYet: 'अद्याप नियुक्त नाही',
  notAvailableYet: 'अद्याप उपलब्ध नाही',
  reportWaterComplaint: 'पाणी तक्रार नोंदवा',
  fillAccurateDetails: 'जलद नगरपालिका कार्यासाठी योग्य तपशील भरा.',
  complaintSubmitted: 'तक्रार यशस्वीरित्या सादर झाली!',
  complaintSaved: 'तुमची तक्रार यशस्वीरित्या सेव झाली आहे.',
  complaintReferenceId: 'तक्रार संदर्भ आयडी',
  useReferenceId: 'या संदर्भ आयडीचा वापर करून तुम्ही तक्रार ट्रॅक करू शकता.',
  fileAnotherComplaint: 'दुसरी तक्रार नोंदवा',
  phoneNumber: 'फोन नंबर',
  category: 'श्रेणी',
  priorityLevel: 'प्राधान्य पातळी',
  wardNumber: 'वॉर्ड क्रमांक',
  specificAddress: 'विशिष्ट पत्ता / landmark',
  descriptionOfIssue: 'समस्येचे वर्णन',
  uploadPhotos: 'फोटो अपलोड करा',
  attachVideo: 'व्हिडिओ जोडा (पर्यायी)',
  submitMunicipalTicket: 'नगरपालिका टिकिट जमा करा',
  submittingComplaint: 'तक्रार जमा होत आहे...',
  pipelineLeakage: 'पाइपलाइन गळती',
  noWaterSupply: 'पाणी पुरवठा नाही',
  dirtyWater: 'गंदे पाणी',
  lowPressure: 'कम दाब',
  waterWastage: 'पाणी वाया',
  illegalConnection: 'अवैध कनेक्शन',
  low: 'कमी',
  medium: 'मध्यम',
  high: 'उच्च',
  emergency: 'आणीबाणी',
  gpsNotSupported: 'या ब्राउझरमध्ये GPS समर्थित नाही.',
  locationPermissionDenied: 'ठिकाण परवानगी नाकारली. तुम्ही पत्ता मॅन्युअली भरू शकता.',
  loginBeforeComplaint: 'तक्रार नोंदवण्यापूर्वी लॉगिन करा.',
  complaintSubmissionFailed: 'तक्रार सादर करण्यात अयशस्वी:',
  somethingWentWrong: 'तक्रार सादर करताना काहीतरी चूक झाली.',
  gpsCoordinatesNotLocked: 'GPS कोऑर्डिनेट लॉक केलेले नाही',
  detectGpsLocation: 'GPS स्थान शोधा',
  activeJobs: 'सक्रिय कामे',
  assignedTeams: 'नियुक्त टीम',
  bookedValue: 'बुक केलेली किंमत',
  requests: 'विनंत्या',
  incomingServiceRequests: 'आताच्या सेवा विनंत्या',
  noLiveServiceRequests: 'कोणतीही लाइव्ह सेवा विनंती नाही.',
  acceptRequest: 'विनंती स्वीकारा',
  startJob: 'काम सुरू करा',
  markCompleted: 'पूर्ण म्हणून चिन्हांकित करा',
  priorityAlerts: 'प्राधान्य सूचना',
  settlementSummary: 'सेटलमेंट सारांश',
  completedJobs: 'पूर्ण कामे',
  pendingPayout: 'प्रलंबित पेमेंट',
  platformCommission: 'प्लॅटफॉर्म कमिशन',
  customerService: 'ग्राहक सेवा',
  bookWaterService: 'पाणी सेवा बुक करा',
  serviceRequestBooked: 'सेवा विनंती बुक झाली',
  requestSent: 'तुमची विनंती सर्वात जवळचे प्राधिकरण संस्थेला पाठवली गेली आहे.',
  service: 'सेवा',
  eta: 'ETA',
  amount: 'रक्कम',
  payment: 'भरणा',
  location: 'ठिकाण',
  pendingConfirmation: 'पुष्टी प्रलंबित',
  chooseService: 'सेवा निवडा',
  bookingDetails: 'बुकिंग तपशील',
  serviceAddress: 'सेवा पत्ता',
  enterFullServiceLocation: 'पूर्ण सेवा पत्ता भरा',
  preferredArrivalWindow: 'पसंतीचा आगमन वेळ',
  paymentMethod: 'पेमेंट पद्धत',
  serviceFee: 'सेवा शुल्क',
  platformFee: 'प्लॅटफॉर्म शुल्क',
  total: 'एकूण',
  payAndConfirm: 'पेमेंट करा आणि बुकिंगची पुष्टी करा',
  customerWallet: 'ग्राहक वॉलेट',
  paymentsAndReceipts: 'पेमेंट आणि रसीद',
  everyBooking: 'प्रत्येक बुकिंगची पेमेंट येथे नोंदवली जाते आणि सद्य सेटलमेंट स्थितीही दिसते.',
  recordedPayments: 'नोंदवलेले पेमेंट',
  noPaymentRecords: 'अद्याप कोणतेही पेमेंट रेकॉर्ड नाही. सेवा बुक करा आणि पहिली रसीद तयार करा.',
  noComplaintsYet: 'तुम्ही अद्याप कोणतीही तक्रार नोंदवलेली नाही.',
  loadingComplaints: 'तुमची तक्रारी लोड होत आहेत...',
  citizenId: 'नागरिक आयडी',
  bookmarks: 'बुकमार्क',
  notifications: 'सूचना',
  noBookmarks: 'अद्याप कोणतेही बुकमार्क किंवा नगरपालिका सूचना नाहीत.',
  noNotifications: 'अद्याप कोणतीही सूचना नाही.',
  civicRewards: 'नागरिक बक्षिसे',
  rewardingParticipation: 'पाण्याच्या नेटवर्कमधील सत्यापित सहभागासाठी बक्षिसे',
  rewardDescription: 'सत्यापित अहवाल, ट्रॅकिंग आणि निराकरण अपडेटद्वारे नागरिक अंक कमवा. अंक मोफत तपासणी आणि सेवा क्रेडिट सारखी सुविधा देऊ शकतात.',
  currentBalance: 'सध्याचा शिल्लक',
  civicPoints: 'नागरिक अंक',
  verifiedReports: 'सत्यापित अहवाल',
  resolvedFollowUps: 'निराकरण केलेले फॉलोअप',
  nextBenefit: 'पुढील फायदा',
  benefitTierActive: 'फायदा स्तर सक्रिय',
  progressTowardBenefit: 'पहिल्या फायद्याकडे प्रगती',
  currentStatus: 'सध्याची स्थिती',
  howPointsEarned: 'अंक कसे कमवले जातात',
  nextUnlockedBenefit: 'पुढील अनलॉक फायदा',
  benefits: 'फायदे',
  citizenServiceRewards: 'नागरिक सेवा बक्षिसे',
  verifiedParticipationOnly: 'फक्त सत्यापित सहभाग',
  programPolicy: 'प्रोग्राम पॉलिसी',
  eligibility: 'सत्यापित समुदाय सहभागावर आधारित पात्रता',
  serviceSupportManaged: 'सेवा सहाय्य नगरपालिका ऑपरेशन्सद्वारे व्यवस्थापित केले जाते',
  active: 'सक्रिय',
  locked: 'लॉक',
  quickLinks: 'त्वरित दुवे',
  fileComplaint: 'तक्रार नोंदवा',
  trackGrievance: 'तक्रार ट्रॅक करा',
  cityAnalytics: 'शहर विश्लेषण',
  toolComparison: 'टूल तुलना',
  categories: 'श्रेणी',
  emergencyHelpline: 'आणीबाणी हेल्पलाइन',
  builtForSmartCities: 'स्मार्ट सिटीसाठी तयार केलेले.',
  summary: 'सारांश',
  submitted: 'सादर झाले',
  assigned: 'नियुक्त',
  inProgress: 'प्रगतीत',
  resolved: 'निराकरण झाले',
  closed: 'बंद',
  status: 'स्थिती',
  priority: 'प्राधान्य',
  address: 'पत्ता',
  details: 'तपशील',
  save: 'जतन करा',
  cancel: 'रद्द करा',
  update: 'अद्यतन',
  keyPlatformFeatures: 'मुख्य प्लॅटफॉर्म वैशिष्ट्ये',
  featureDescription: 'अतिशय वेग, पारदर्शकता आणि नगरपालिका कार्यक्षमता यासाठी तयार केलेले.',
  realTimeTracking: 'रिअल-टाइम ट्रॅकिंग',
  proof: 'फोटो आणि व्हिडिओ पुरावे',
  gpsPrecision: 'GPS अचूकता',
  authorityDashboardFeature: 'प्राधिकरण डॅशबोर्ड',
  emergencySosMode: 'आणीबाणी SOS मोड',
  waterAnalytics: 'पाणी विश्लेषण',
  howJalSahayWorks: 'जळसहाय कसे काम करते',
  loginRegisterStep: 'लॉगिन / नोंदणी',
  submitIssueStep: 'समस्या सादर करा',
  authorityReviewStep: 'प्राधिकरण पुनरावलोकन',
  issueResolvedStep: 'समस्या निराकरण झाली',
  overview: 'आढावा आणि अपडेट्स',
  reportComplaintDescription: 'पाणी समस्या नोंदवा',
  trackStatusDescription: 'नोंदवलेल्या समस्येचे ट्रॅक करा',
  analyticsDescription: 'सेवा आणि क्षेत्राची माहिती',
  comparisonDescription: 'सेवा कामगिरीची तुलना करा',
  blogDescription: 'जल नेटवर्क अपडेट्स',
  rewardsDescription: 'तुमची सत्यापित सहभागिता',
  operationsDescription: 'प्राधिकरण विनंत्या व्यवस्थापित करा',
  dashboardDescription: 'तुमची सेवा माहिती',
  bookServiceDescription: 'पाणी मदतीसाठी विनंती करा',
  paymentsDescription: 'रसीद आणि इतिहास',
  profileDescription: 'तुमचे प्रोफाइल',
  support: 'सहाय्य',
  description: 'वर्णन',
  backToHome: 'मुख्यपृष्ठावर परत',
  loading: 'लोड होत आहे',
  servicePartner: 'जवळचे प्राधिकरण सहयोगी',
  user: 'वापरकर्ता',
  waterServiceNetwork: 'जल सेवा नेटवर्क',
  connectReportResolve: 'जोडा, तक्रार नोंदवा आणि विश्वासाने निराकरण मिळवा.',
  authorityAccount: 'प्राधिकरण खाते',
  customerAccount: 'ग्राहक खाते',
  yourWorkspace: 'तुमचे कार्यक्षेत्र',
  exploreJalSahay: 'जळसहाय पहा',
  signOut: 'साइन आउट',
  authorityPortal: 'प्राधिकरण पोर्टल',
  operationsDashboard: 'कार्यवाही डॅशबोर्ड',
  rewardingVerifiedParticipation: 'जल नेटवर्कमधील सत्यापित सहभागासाठी बक्षिसे',
  pointEarning: 'अंक कसे मिळवायचे',
  inProgressLabel: 'प्रगतीत',
  progressTo: 'प्रगती:',
  onlineStatusTracking: 'ऑनलाइन स्थिती ट्रॅकिंग',
  photoVideoUpload: 'फोटो आणि व्हिडिओ अपलोड',
  exactGpsGeotagging: 'अचूक GPS जिओटॅगिंग',
  realTimePushAlerts: 'रिअल-टाइम पुश सूचना',
  wardAnalytics: 'वॉर्ड विश्लेषण',
  avgResponseTime: 'सरासरी प्रतिसाद वेळ',
  traditionalVsJalSahay: 'पारंपरिक प्रणाली विरुद्ध जळसहाय',
  whyModernCities: 'आधुनिक शहरे स्वयंचलित जल पोर्टल व्यवस्थापन का स्वीकारत आहेत.',
  feature: 'वैशिष्ट्य',
  traditionalSystem: 'पारंपरिक प्रणाली',
  jalsahaySmartSystem: 'जळसहाय स्मार्ट प्रणाली',
  waterConservationNews: 'जल संवर्धन आणि नगरपालिका बातम्या',
  articlesGuidelines: 'स्मार्ट जल व्यवस्थापनावरील लेख आणि मार्गदर्शक सूचना.',
  by: 'द्वारे',
  basicInspectionCredit: 'मूलभूत तपासणी क्रेडिट',
  freeLeakInspection: 'मोफत गळती तपासणी किंवा मूलभूत सेवा मूल्यांकन.',
  complimentaryVisit: 'मोफत भेट',
  priorityServiceSupport: 'प्राधान्य सेवा सहाय्य',
  priorityScheduling: 'दुरुस्ती आणि देखभाल सहाय्यासाठी प्राधान्य वेळापत्रक.',
  fastTrackService: 'जलद सेवा',
  quarterlyWaterCheck: 'त्रैमासिक पाणी तपासणी',
  freeWaterQuality: 'प्रत्येक तिमाहीत एक मोफत पाणी गुणवत्ता आणि दाब मूल्यांकन.',
  freeUtilityCheck: 'मोफत उपयोगिता तपासणी',
  annualCivicCredit: 'वार्षिक नागरिक क्रेडिट',
  waivedServiceFee: 'सेवा शुल्क माफ किंवा संपूर्ण उपयोगिता सहाय्य पॅकेज.',
  freeServiceBundle: 'मोफत सेवा पॅकेज',
  submitVerifiedComplaint: 'सत्यापित तक्रार नोंदवा',
  requiredForReporting: 'पाणी गळती, दाब किंवा दूषितपणा नोंदवण्यासाठी आवश्यक.',
  trackComplaintProgress: 'तक्रारीची प्रगती ट्रॅक करा',
  helpsTransparency: 'पारदर्शकता आणि फॉलो-अप पूर्ण करण्यास मदत करते.',
  successfulResolutionUpdate: 'यशस्वी निराकरण अपडेट द्या',
  rewardsFixConfirmation: 'दुरुस्ती किंवा बंद होण्याची पुष्टी करणाऱ्या वापरकर्त्यांना बक्षीस.',
  repeatedQualityReporting: 'सातत्यपूर्ण गुणवत्तापूर्ण अहवाल',
  sustainedCivicEngagement: 'समस्या नोंदवण्यात सातत्यपूर्ण नागरिक सहभागासाठी.',
  liveMunicipalOperations: 'लाइव्ह नगरपालिका कार्यवाही',
  waterIntelligenceDashboard: 'पाणी माहिती डॅशबोर्ड',
  realComplaintWeather: 'वास्तविक तक्रार डेटा आणि लाइव्ह हवामान माहिती',
  refreshData: 'डेटा रिफ्रेश करा',
  highestAttentionRequired: 'सर्वाधिक लक्ष आवश्यक',
  priorityScore: 'प्राधान्य स्कोअर',
  totalComplaints: 'एकूण तक्रारी',
  open: 'उघड्या',
  emergencyLabel: 'आणीबाणी',
  highPriority: 'उच्च प्राधान्य',
  criticalZones: 'गंभीर क्षेत्रे',
  immediateMonitoring: 'तातडीच्या निरीक्षणाची शिफारस',
  highRiskZones: 'उच्च जोखीम क्षेत्रे',
  increasedAttention: 'अधिक सेवा लक्ष आवश्यक',
  monitoredZones: 'निरीक्षणातील क्षेत्रे',
  weatherComplaintAreas: 'हवामान आणि तक्रार निरीक्षण क्षेत्रे',
  complaintsByCategory: 'श्रेणीनुसार तक्रारी',
  complaintsByWard: 'वॉर्डनुसार तक्रारी',
  complaintStatus: 'तक्रार स्थिती',
  serviceRiskAnalysis: 'सेवा जोखीम विश्लेषण',
  zone: 'क्षेत्र',
  risk: 'जोखीम',
  score: 'स्कोअर',
  complaints: 'तक्रारी',
  rain: 'पाऊस',
  rainProbability: 'पावसाची शक्यता',
  action: 'कार्यवाही',
  immediateInspection: 'तातडीची तपासणी',
  increaseMonitoring: 'निरीक्षण वाढवा',
  monitor: 'निरीक्षण करा',
  normalOperations: 'सामान्य कार्यवाही',
  riskScoreNote: 'जोखीम स्कोअर लाइव्ह हवामान अंदाज आणि तक्रार क्रियाकलापावर आधारित निर्णय-सहाय्य संकेतक आहेत. ते घटनांचे हमखास अंदाज नाहीत.',
  submittedCount: 'नोंदवलेल्या तक्रारी',
  pendingCount: 'प्रलंबित',
  averageResponseTime: 'सरासरी प्रतिसाद वेळ',
  satisfaction: 'समाधान',
  realTimeTrackingDesc: 'नियुक्तीपासून दुरुस्ती पथक येईपर्यंत प्रत्येक टप्पा ट्रॅक करा.',
  photoVideoProofDesc: 'जलद पडताळणीसाठी जिओटॅग केलेले फोटो आणि व्हिडिओ जोडा.',
  gpsPrecisionDesc: 'पाण्याच्या गळतीचे अचूक स्थान आणि निर्देशांक शोधा.',
  authorityDashboardDesc: 'अभियंत्यांना कार्यवाहीसाठी वॉर्ड अपडेट्स त्वरित मिळतात.',
  emergencySosDesc: 'मोठ्या पाइप फुटणे आणि दूषित पुरवठ्यासाठी उच्च प्राधान्य सूचना.',
  waterAnalyticsDesc: 'वारंवार होणाऱ्या समस्यांवरील आणि वॉर्ड कामगिरीवरील माहिती.',
  loginRegisterDesc: 'Google किंवा ईमेलद्वारे काही सेकंदात नोंदणी करा.',
  submitIssueDesc: 'श्रेणी निवडा, फोटो घ्या आणि GPS सेट करा.',
  authorityReviewDesc: 'वॉर्ड अभियंता त्वरित नियुक्त केला जातो.',
  issueResolvedDesc: 'रिअल-टाइम निराकरण स्थिती मिळवा आणि कामाला रेट करा.',
  userProfileSettings: 'वापरकर्ता प्रोफाइल सेटिंग्ज',
  registeredWard: 'नोंदणीकृत वॉर्ड',
  detectYourLocationFirst: 'प्रथम आपले स्थान शोधा.',
  yourComplaintLocation: 'तुमच्या तक्रारीचे स्थान',
  liveComplaintMap: 'लाइव्ह तक्रार नकाशा',
  complaintLocationsSupabase: 'Supabase वरील तक्रार स्थाने',
  useMyGps: 'माझे GPS वापरा',
  locationPermissionMap: 'स्थानाची परवानगी नाकारली. कृपया स्थानाची परवानगी द्या.',
  blog1Title: 'घरी पाणी वाचवण्याचे 10 सिद्ध मार्ग',
  blog1Category: 'जल संवर्धन',
  blog1Summary: 'दररोजचे छोटे बदल घरातील पाण्याचा वापर आणि अनावश्यक अपव्यय कमी करू शकतात.',
  blog2Title: 'पाणी पुरवठ्याची समस्या कशी नोंदवावी',
  blog2Category: 'नागरिक सेवा',
  blog2Summary: 'गळती, गढूळ पाणी, कमी दाब आणि पाणी पुरवठ्याच्या समस्या नागरिक कशा नोंदवू शकतात ते जाणून घ्या.',
  blog3Title: 'पाण्याच्या गळतीकडे त्वरित लक्ष देणे का आवश्यक आहे',
  blog3Category: 'जल पायाभूत सुविधा',
  blog3Summary: 'लहान गळती मोठ्या पायाभूत समस्या बनू शकतात आणि मोठ्या प्रमाणात प्रक्रिया केलेले पाणी वाया घालवू शकतात.',
  blog4Title: 'हवामान आणि पाणी पुरवठा व्यवस्थापन',
  blog4Category: 'स्मार्ट जल व्यवस्थापन',
  blog4Summary: 'हवामानाची माहिती नगरपालिका पथकांना मुसळधार पाऊस, पूर, पाणी दूषित होणे आणि पुरवठ्यावरील ताणासाठी तयार होण्यास मदत करू शकते.'
};

const makeRegionalLanguage = (overrides) => ({
  ...baseEnglish,
  ...overrides,
  overview: overrides.overview || overrides.home,
  reportComplaintDescription: overrides.reportComplaintDescription || overrides.report,
  trackStatusDescription: overrides.trackStatusDescription || overrides.track,
  analyticsDescription: overrides.analyticsDescription || overrides.analytics,
  comparisonDescription: overrides.comparisonDescription || overrides.comparison,
  blogDescription: overrides.blogDescription || overrides.blog,
  rewardsDescription: overrides.rewardsDescription || overrides.rewards,
  operationsDescription: overrides.operationsDescription || overrides.operations,
  dashboardDescription: overrides.dashboardDescription || overrides.dashboard,
  bookServiceDescription: overrides.bookServiceDescription || overrides.bookService,
  paymentsDescription: overrides.paymentsDescription || overrides.payments,
  profileDescription: overrides.profileDescription || overrides.profile,
  realTimeTrackingDesc: overrides.realTimeTrackingDesc || overrides.realTimeTracking,
  photoVideoProofDesc: overrides.photoVideoProofDesc || overrides.proof,
  gpsPrecisionDesc: overrides.gpsPrecisionDesc || overrides.gpsPrecision,
  authorityDashboardDesc: overrides.authorityDashboardDesc || overrides.authorityDashboardFeature,
  emergencySosDesc: overrides.emergencySosDesc || overrides.emergencySosMode,
  waterAnalyticsDesc: overrides.waterAnalyticsDesc || overrides.waterAnalytics,
  loginRegisterDesc: overrides.loginRegisterDesc || overrides.loginRegisterStep,
  submitIssueDesc: overrides.submitIssueDesc || overrides.submitIssueStep,
  authorityReviewDesc: overrides.authorityReviewDesc || overrides.authorityReviewStep,
  issueResolvedDesc: overrides.issueResolvedDesc || overrides.issueResolvedStep,
  blog1Title: overrides.blog1Title || overrides.blog,
  blog1Category: overrides.blog1Category || overrides.blog,
  blog1Summary: overrides.blog1Summary || overrides.blog,
  blog2Title: overrides.blog2Title || overrides.blog,
  blog2Category: overrides.blog2Category || overrides.blog,
  blog2Summary: overrides.blog2Summary || overrides.blog,
  blog3Title: overrides.blog3Title || overrides.blog,
  blog3Category: overrides.blog3Category || overrides.blog,
  blog3Summary: overrides.blog3Summary || overrides.blog,
  blog4Title: overrides.blog4Title || overrides.blog,
  blog4Category: overrides.blog4Category || overrides.blog,
  blog4Summary: overrides.blog4Summary || overrides.blog
});

const gujarati = makeRegionalLanguage({
  badge: 'નવી પેઢીની નગરપાલિકા ટેકનોલોજી', title: 'સ્માર્ટ પાણી ફરિયાદ વ્યવસ્થાપન સિસ્ટમ', subtitle: 'પાણી પુરવઠાની સમસ્યાઓ નોંધાવો, ઉકેલની સ્થિતિ જુઓ અને લીક મુક્ત શહેર બનાવવામાં મદદ કરો.',
  reportComplaint: 'ફરિયાદ નોંધાવો', trackComplaint: 'ફરિયાદ ટ્રૅક કરો', serviceDesk: 'સેવા ડેસ્ક ઓનલાઈન', reportIssue: 'સમસ્યા નોંધાવો', home: 'હોમ', report: 'ફરિયાદ નોંધણી', track: 'સ્થિતિ ટ્રૅક કરો', analytics: 'વિશ્લેષણ', comparison: 'સરખામણી', blog: 'સમાચાર અને બ્લોગ', rewards: 'નાગરિક પુરસ્કારો', operations: 'કામગીરી', dashboard: 'ડેશબોર્ડ', bookService: 'સેવા બુક કરો', payments: 'ચુકવણીઓ', profile: 'પ્રોફાઇલ', loginRegister: 'લૉગિન અથવા નોંધણી', menu: 'મેનૂ', navigateTitle: 'જલસહાય નેવિગેટ કરો', languageLabel: 'ભાષા', chooseLanguage: 'ભાષા પસંદ કરો',
  keyPlatformFeatures: 'મુખ્ય પ્લેટફોર્મ સુવિધાઓ', featureDescription: 'ઝડપ, પારદર્શિતા અને નગરપાલિકા કાર્યક્ષમતા માટે બનાવેલ.', realTimeTracking: 'રીઅલ-ટાઇમ ટ્રૅકિંગ', proof: 'ફોટો અને વીડિયો પુરાવો', gpsPrecision: 'GPS ચોકસાઈ', authorityDashboardFeature: 'સત્તાધિકારી ડેશબોર્ડ', emergencySosMode: 'કટોકટી SOS મોડ', waterAnalytics: 'પાણી વિશ્લેષણ', howJalSahayWorks: 'જલસહાય કેવી રીતે કામ કરે છે',
  realTimeTrackingDesc: 'નિયુક્તિથી સમારકામ ટીમ આવવા સુધીના તબક્કા જુઓ.', photoVideoProofDesc: 'ઝડપી ચકાસણી માટે જિયોટૅગ ફોટા અને વીડિયો ઉમેરો.', gpsPrecisionDesc: 'પાણી લીકનું ચોક્કસ સ્થાન શોધો.', authorityDashboardDesc: 'કામગીરી માટે એન્જિનિયરોને વોર્ડ અપડેટ તરત મળે છે.', emergencySosDesc: 'મોટી પાઇપ તૂટવા અને દૂષિત પાણી માટે ઉચ્ચ પ્રાથમિકતા સૂચના.', waterAnalyticsDesc: 'વારંવારની સમસ્યાઓ અને વોર્ડ કામગીરીની માહિતી.',
  liveMunicipalOperations: 'લાઇવ નગરપાલિકા કામગીરી', waterIntelligenceDashboard: 'પાણી માહિતી ડેશબોર્ડ', refreshData: 'ડેટા રિફ્રેશ કરો', totalComplaints: 'કુલ ફરિયાદો', open: 'ખુલ્લી', resolved: 'ઉકેલાઈ', pendingCount: 'બાકી', satisfaction: 'સંતોષ', liveComplaintMap: 'લાઇવ ફરિયાદ નકશો', useMyGps: 'મારું GPS વાપરો',
  waterConservationNews: 'પાણી સંરક્ષણ અને નગરપાલિકા સમાચાર', articlesGuidelines: 'સ્માર્ટ પાણી વ્યવસ્થાપન અંગે લેખો અને માર્ગદર્શિકા.', userProfileSettings: 'વપરાશકર્તા પ્રોફાઇલ સેટિંગ્સ', registeredWard: 'નોંધાયેલ વોર્ડ', signOut: 'સાઇન આઉટ', closeNavigation: 'નેવિગેશન બંધ કરો', authorityAccount: 'સત્તાધિકારી ખાતું', customerAccount: 'ગ્રાહક ખાતું', yourWorkspace: 'તમારું કાર્યક્ષેત્ર', exploreJalSahay: 'જલસહાય જુઓ',
  blog1Title: 'ઘરે પાણી બચાવવાની 10 સાબિત રીતો', blog1Category: 'પાણી સંરક્ષણ', blog1Summary: 'રોજિંદા નાના ફેરફારો ઘરેલું પાણી વપરાશ ઘટાડી શકે છે.', blog2Title: 'પાણી પુરવઠાની સમસ્યા કેવી રીતે નોંધાવવી', blog2Category: 'નાગરિક સેવાઓ', blog2Summary: 'લીક, ગંદુ પાણી, ઓછું દબાણ અને પુરવઠાની સમસ્યાઓ નોંધાવવાનું શીખો.'
});

const tamil = makeRegionalLanguage({
  badge: 'அடுத்த தலைமுறை நகராட்சி தொழில்நுட்பம்', title: 'ஸ்மார்ட் குடிநீர் புகார் மேலாண்மை அமைப்பு', subtitle: 'நீர் வழங்கல் பிரச்சினைகளைப் பதிவு செய்து, தீர்வு நிலையைப் பார்த்து, கசிவு இல்லாத நகரத்தை உருவாக்க உதவுங்கள்.', reportComplaint: 'புகார் பதிவு', trackComplaint: 'புகாரைத் தொடர்க', serviceDesk: 'சேவை மேசை ஆன்லைன்', reportIssue: 'பிரச்சினையைப் பதிவு செய்க', home: 'முகப்பு', report: 'புகார் பதிவு', track: 'நிலையைத் தொடர்க', analytics: 'பகுப்பாய்வு', comparison: 'ஒப்பீடு', blog: 'செய்திகள் மற்றும் வலைப்பதிவு', rewards: 'குடிமக்கள் வெகுமதி', operations: 'செயல்பாடுகள்', dashboard: 'டாஷ்போர்டு', bookService: 'சேவையைப் பதிவு செய்க', payments: 'கட்டணங்கள்', profile: 'சுயவிவரம்', loginRegister: 'உள்நுழை அல்லது பதிவு செய்க', menu: 'பட்டியல்', navigateTitle: 'ஜலசஹாய் வழிசெலுத்தல்', languageLabel: 'மொழி', chooseLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்', keyPlatformFeatures: 'முக்கிய தள அம்சங்கள்', featureDescription: 'வேகம், வெளிப்படைத்தன்மை மற்றும் நகராட்சி திறனுக்காக உருவாக்கப்பட்டது.', realTimeTracking: 'நிகழ்நேர கண்காணிப்பு', proof: 'புகைப்படம் மற்றும் வீடியோ ஆதாரம்', gpsPrecision: 'GPS துல்லியம்', authorityDashboardFeature: 'அதிகாரி டாஷ்போர்டு', emergencySosMode: 'அவசர SOS முறை', waterAnalytics: 'நீர் பகுப்பாய்வு', howJalSahayWorks: 'ஜலசஹாய் எவ்வாறு செயல்படுகிறது', realTimeTrackingDesc: 'ஒதுக்கீட்டிலிருந்து பழுது நீக்கும் குழு வருகை வரை கண்காணிக்கவும்.', photoVideoProofDesc: 'விரைவான சரிபார்ப்புக்கு புவிக்குறியிடப்பட்ட ஊடகத்தைச் சேர்க்கவும்.', gpsPrecisionDesc: 'நீர் கசிவு இடத்தைத் துல்லியமாகக் கண்டறியவும்.', waterConservationNews: 'நீர் பாதுகாப்பு மற்றும் நகராட்சி செய்திகள்', articlesGuidelines: 'ஸ்மார்ட் நீர் மேலாண்மை பற்றிய கட்டுரைகள் மற்றும் வழிகாட்டிகள்.', userProfileSettings: 'பயனர் சுயவிவர அமைப்புகள்', registeredWard: 'பதிவு செய்த வார்டு', signOut: 'வெளியேறு', liveComplaintMap: 'நேரடி புகார் வரைபடம்', useMyGps: 'என் GPS-ஐப் பயன்படுத்து'
});

const telugu = makeRegionalLanguage({ badge: 'తరువాతి తరం మునిసిపల్ టెక్నాలజీ', title: 'స్మార్ట్ నీటి ఫిర్యాదు నిర్వహణ వ్యవస్థ', reportComplaint: 'ఫిర్యాదు నమోదు', trackComplaint: 'ఫిర్యాదును ట్రాక్ చేయండి', serviceDesk: 'సేవా డెస్క్ ఆన్‌లైన్', reportIssue: 'సమస్యను నివేదించండి', home: 'హోమ్', report: 'ఫిర్యాదు నివేదన', track: 'స్థితిని ట్రాక్ చేయండి', analytics: 'విశ్లేషణ', comparison: 'పోలిక', blog: 'వార్తలు మరియు బ్లాగ్', rewards: 'పౌర బహుమతులు', operations: 'కార్యకలాపాలు', dashboard: 'డాష్‌బోర్డ్', bookService: 'సేవను బుక్ చేయండి', payments: 'చెల్లింపులు', profile: 'ప్రొఫైల్', loginRegister: 'లాగిన్ లేదా నమోదు', menu: 'మెను', navigateTitle: 'జలసహాయ్ నావిగేట్ చేయండి', languageLabel: 'భాష', chooseLanguage: 'భాషను ఎంచుకోండి', keyPlatformFeatures: 'ప్రధాన ప్లాట్‌ఫారమ్ లక్షణాలు', realTimeTracking: 'రియల్ టైమ్ ట్రాకింగ్', proof: 'ఫోటో మరియు వీడియో ఆధారం', gpsPrecision: 'GPS ఖచ్చితత్వం', authorityDashboardFeature: 'అధికార డాష్‌బోర్డ్', emergencySosMode: 'అత్యవసర SOS విధానం', waterAnalytics: 'నీటి విశ్లేషణ', howJalSahayWorks: 'జలసహాయ్ ఎలా పనిచేస్తుంది', waterConservationNews: 'నీటి సంరక్షణ మరియు మునిసిపల్ వార్తలు', articlesGuidelines: 'స్మార్ట్ నీటి నిర్వహణపై వ్యాసాలు మరియు మార్గదర్శకాలు.', userProfileSettings: 'వినియోగదారు ప్రొఫైల్ సెట్టింగ్‌లు', registeredWard: 'నమోదైన వార్డు', signOut: 'సైన్ అవుట్', liveComplaintMap: 'లైవ్ ఫిర్యాదు మ్యాప్', useMyGps: 'నా GPS ఉపయోగించండి' });

const bengali = makeRegionalLanguage({ badge: 'পরবর্তী প্রজন্মের পৌর প্রযুক্তি', title: 'স্মার্ট জল অভিযোগ ব্যবস্থাপনা ব্যবস্থা', reportComplaint: 'অভিযোগ জানান', trackComplaint: 'অভিযোগ অনুসরণ করুন', serviceDesk: 'সেবা ডেস্ক অনলাইন', reportIssue: 'সমস্যা জানান', home: 'হোম', report: 'অভিযোগ জানান', track: 'অবস্থা দেখুন', analytics: 'বিশ্লেষণ', comparison: 'তুলনা', blog: 'খবর ও ব্লগ', rewards: 'নাগরিক পুরস্কার', operations: 'কার্যক্রম', dashboard: 'ড্যাশবোর্ড', bookService: 'সেবা বুক করুন', payments: 'পেমেন্ট', profile: 'প্রোফাইল', loginRegister: 'লগইন বা নিবন্ধন', menu: 'মেনু', navigateTitle: 'জলসহায় নেভিগেট করুন', languageLabel: 'ভাষা', chooseLanguage: 'ভাষা বেছে নিন', keyPlatformFeatures: 'প্রধান প্ল্যাটফর্ম বৈশিষ্ট্য', realTimeTracking: 'রিয়েল-টাইম ট্র্যাকিং', proof: 'ছবি ও ভিডিও প্রমাণ', gpsPrecision: 'GPS নির্ভুলতা', authorityDashboardFeature: 'কর্তৃপক্ষ ড্যাশবোর্ড', emergencySosMode: 'জরুরি SOS মোড', waterAnalytics: 'জল বিশ্লেষণ', howJalSahayWorks: 'জলসহায় কীভাবে কাজ করে', waterConservationNews: 'জল সংরক্ষণ ও পৌর সংবাদ', articlesGuidelines: 'স্মার্ট জল ব্যবস্থাপনা সম্পর্কে নিবন্ধ ও নির্দেশিকা।', userProfileSettings: 'ব্যবহারকারী প্রোফাইল সেটিংস', registeredWard: 'নিবন্ধিত ওয়ার্ড', signOut: 'সাইন আউট', liveComplaintMap: 'লাইভ অভিযোগ মানচিত্র', useMyGps: 'আমার GPS ব্যবহার করুন' });

const kannada = makeRegionalLanguage({ badge: 'ಮುಂದಿನ ತಲೆಮಾರಿನ ನಗರ ತಂತ್ರಜ್ಞಾನ', title: 'ಸ್ಮಾರ್ಟ್ ನೀರಿನ ದೂರು ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ', reportComplaint: 'ದೂರು ದಾಖಲಿಸಿ', trackComplaint: 'ದೂರು ಪರಿಶೀಲಿಸಿ', serviceDesk: 'ಸೇವಾ ಡೆಸ್ಕ್ ಆನ್‌ಲೈನ್', reportIssue: 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ', home: 'ಮುಖಪುಟ', report: 'ದೂರು ವರದಿ', track: 'ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ', analytics: 'ವಿಶ್ಲೇಷಣೆ', comparison: 'ಹೋಲಿಕೆ', blog: 'ಸುದ್ದಿ ಮತ್ತು ಬ್ಲಾಗ್', rewards: 'ನಾಗರಿಕ ಬಹುಮಾನಗಳು', operations: 'ಕಾರ್ಯಾಚರಣೆ', dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', bookService: 'ಸೇವೆ ಬುಕ್ ಮಾಡಿ', payments: 'ಪಾವತಿಗಳು', profile: 'ಪ್ರೊಫೈಲ್', loginRegister: 'ಲಾಗಿನ್ ಅಥವಾ ನೋಂದಣಿ', menu: 'ಮೆನು', navigateTitle: 'ಜಲಸಹಾಯ್ ನ್ಯಾವಿಗೇಟ್ ಮಾಡಿ', languageLabel: 'ಭಾಷೆ', chooseLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ', keyPlatformFeatures: 'ಮುಖ್ಯ ವೇದಿಕೆ ವೈಶಿಷ್ಟ್ಯಗಳು', realTimeTracking: 'ನೈಜ-ಸಮಯ ಟ್ರ್ಯಾಕಿಂಗ್', proof: 'ಫೋಟೋ ಮತ್ತು ವೀಡಿಯೊ ಸಾಕ್ಷ್ಯ', gpsPrecision: 'GPS ನಿಖರತೆ', authorityDashboardFeature: 'ಅಧಿಕಾರಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', emergencySosMode: 'ತುರ್ತು SOS ಮೋಡ್', waterAnalytics: 'ನೀರಿನ ವಿಶ್ಲೇಷಣೆ', howJalSahayWorks: 'ಜಲಸಹಾಯ್ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ', waterConservationNews: 'ನೀರಿನ ಸಂರಕ್ಷಣೆ ಮತ್ತು ನಗರ ಸುದ್ದಿ', articlesGuidelines: 'ಸ್ಮಾರ್ಟ್ ನೀರು ನಿರ್ವಹಣೆಯ ಲೇಖನಗಳು ಮತ್ತು ಮಾರ್ಗದರ್ಶಿಗಳು.', userProfileSettings: 'ಬಳಕೆದಾರ ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು', registeredWard: 'ನೋಂದಾಯಿತ ವಾರ್ಡ್', signOut: 'ಸೈನ್ ಔಟ್', liveComplaintMap: 'ಲೈವ್ ದೂರು ನಕ್ಷೆ', useMyGps: 'ನನ್ನ GPS ಬಳಸಿ' });

const malayalam = makeRegionalLanguage({ badge: 'അടുത്ത തലമുറ നഗര സാങ്കേതികവിദ്യ', title: 'സ്മാർട്ട് ജല പരാതി മാനേജ്മെന്റ് സംവിധാനം', reportComplaint: 'പരാതി നൽകുക', trackComplaint: 'പരാതി പിന്തുടരുക', serviceDesk: 'സേവന ഡെസ്ക് ഓൺലൈൻ', reportIssue: 'പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക', home: 'ഹോം', report: 'പരാതി റിപ്പോർട്ട്', track: 'സ്ഥിതി പിന്തുടരുക', analytics: 'വിശകലനം', comparison: 'താരതമ്യം', blog: 'വാർത്തകളും ബ്ലോഗും', rewards: 'പൗര സമ്മാനങ്ങൾ', operations: 'പ്രവർത്തനങ്ങൾ', dashboard: 'ഡാഷ്ബോർഡ്', bookService: 'സേവനം ബുക്ക് ചെയ്യുക', payments: 'പേയ്മെന്റുകൾ', profile: 'പ്രൊഫൈൽ', loginRegister: 'ലോഗിൻ അല്ലെങ്കിൽ രജിസ്റ്റർ', menu: 'മെനു', navigateTitle: 'ജൽസഹായ് നാവിഗേറ്റ് ചെയ്യുക', languageLabel: 'ഭാഷ', chooseLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക', keyPlatformFeatures: 'പ്രധാന പ്ലാറ്റ്ഫോം സവിശേഷതകൾ', realTimeTracking: 'തത്സമയ ട്രാക്കിംഗ്', proof: 'ഫോട്ടോയും വീഡിയോ തെളിവും', gpsPrecision: 'GPS കൃത്യത', authorityDashboardFeature: 'അധികാരി ഡാഷ്ബോർഡ്', emergencySosMode: 'അടിയന്തര SOS മോഡ്', waterAnalytics: 'ജല വിശകലനം', howJalSahayWorks: 'ജൽസഹായ് എങ്ങനെ പ്രവർത്തിക്കുന്നു', waterConservationNews: 'ജല സംരക്ഷണവും നഗര വാർത്തകളും', articlesGuidelines: 'സ്മാർട്ട് ജല മാനേജ്മെന്റിനെക്കുറിച്ചുള്ള ലേഖനങ്ങളും മാർഗ്ഗനിർദ്ദേശങ്ങളും.', userProfileSettings: 'ഉപയോക്തൃ പ്രൊഫൈൽ ക്രമീകരണങ്ങൾ', registeredWard: 'രജിസ്റ്റർ ചെയ്ത വാർഡ്', signOut: 'സൈൻ ഔട്ട്', liveComplaintMap: 'തത്സമയ പരാതി മാപ്പ്', useMyGps: 'എന്റെ GPS ഉപയോഗിക്കുക' });

const punjabi = makeRegionalLanguage({ badge: 'ਨਵੀਂ ਪੀੜ੍ਹੀ ਦੀ ਨਗਰਪਾਲਿਕਾ ਤਕਨਾਲੋਜੀ', title: 'ਸਮਾਰਟ ਪਾਣੀ ਸ਼ਿਕਾਇਤ ਪ੍ਰਬੰਧਨ ਪ੍ਰਣਾਲੀ', reportComplaint: 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ', trackComplaint: 'ਸ਼ਿਕਾਇਤ ਟਰੈਕ ਕਰੋ', serviceDesk: 'ਸੇਵਾ ਡੈਸਕ ਆਨਲਾਈਨ', reportIssue: 'ਸਮੱਸਿਆ ਦੱਸੋ', home: 'ਘਰ', report: 'ਸ਼ਿਕਾਇਤ ਰਿਪੋਰਟ', track: 'ਸਥਿਤੀ ਵੇਖੋ', analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ', comparison: 'ਤੁਲਨਾ', blog: 'ਖ਼ਬਰਾਂ ਅਤੇ ਬਲੌਗ', rewards: 'ਨਾਗਰਿਕ ਇਨਾਮ', operations: 'ਕਾਰਵਾਈ', dashboard: 'ਡੈਸ਼ਬੋਰਡ', bookService: 'ਸੇਵਾ ਬੁੱਕ ਕਰੋ', payments: 'ਭੁਗਤਾਨ', profile: 'ਪ੍ਰੋਫਾਈਲ', loginRegister: 'ਲੌਗਇਨ ਜਾਂ ਰਜਿਸਟਰ', menu: 'ਮੇਨੂ', navigateTitle: 'ਜਲਸਹਾਇ ਨੈਵੀਗੇਟ ਕਰੋ', languageLabel: 'ਭਾਸ਼ਾ', chooseLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ', keyPlatformFeatures: 'ਮੁੱਖ ਪਲੇਟਫਾਰਮ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ', realTimeTracking: 'ਰੀਅਲ-ਟਾਈਮ ਟਰੈਕਿੰਗ', proof: 'ਫੋਟੋ ਅਤੇ ਵੀਡੀਓ ਸਬੂਤ', gpsPrecision: 'GPS ਸ਼ੁੱਧਤਾ', authorityDashboardFeature: 'ਅਧਿਕਾਰੀ ਡੈਸ਼ਬੋਰਡ', emergencySosMode: 'ਐਮਰਜੈਂਸੀ SOS ਮੋਡ', waterAnalytics: 'ਪਾਣੀ ਵਿਸ਼ਲੇਸ਼ਣ', howJalSahayWorks: 'ਜਲਸਹਾਇ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ', waterConservationNews: 'ਪਾਣੀ ਸੰਭਾਲ ਅਤੇ ਨਗਰਪਾਲਿਕਾ ਖ਼ਬਰਾਂ', articlesGuidelines: 'ਸਮਾਰਟ ਪਾਣੀ ਪ੍ਰਬੰਧਨ ਬਾਰੇ ਲੇਖ ਅਤੇ ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼।', userProfileSettings: 'ਉਪਭੋਗਤਾ ਪ੍ਰੋਫਾਈਲ ਸੈਟਿੰਗਾਂ', registeredWard: 'ਰਜਿਸਟਰਡ ਵਾਰਡ', signOut: 'ਸਾਈਨ ਆਊਟ', liveComplaintMap: 'ਲਾਈਵ ਸ਼ਿਕਾਇਤ ਨਕਸ਼ਾ', useMyGps: 'ਮੇਰਾ GPS ਵਰਤੋ' });

const odia = makeRegionalLanguage({ badge: 'ନୂତନ ପିଢ଼ିର ପୌର ପ୍ରଯୁକ୍ତି', title: 'ସ୍ମାର୍ଟ ଜଳ ଅଭିଯୋଗ ପରିଚାଳନା ବ୍ୟବସ୍ଥା', reportComplaint: 'ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ', trackComplaint: 'ଅଭିଯୋଗ ଟ୍ରାକ୍ କରନ୍ତୁ', serviceDesk: 'ସେବା ଡେସ୍କ ଅନଲାଇନ୍', reportIssue: 'ସମସ୍ୟା ରିପୋର୍ଟ କରନ୍ତୁ', home: 'ମୁଖ୍ୟ ପୃଷ୍ଠା', report: 'ଅଭିଯୋଗ ରିପୋର୍ଟ', track: 'ସ୍ଥିତି ଦେଖନ୍ତୁ', analytics: 'ବିଶ୍ଳେଷଣ', comparison: 'ତୁଳନା', blog: 'ସମ୍ବାଦ ଓ ବ୍ଲଗ୍', rewards: 'ନାଗରିକ ପୁରସ୍କାର', operations: 'କାର୍ଯ୍ୟ', dashboard: 'ଡ୍ୟାସବୋର୍ଡ', bookService: 'ସେବା ବୁକ୍ କରନ୍ତୁ', payments: 'ଦେୟ', profile: 'ପ୍ରୋଫାଇଲ୍', loginRegister: 'ଲଗଇନ୍ କିମ୍ବା ପଞ୍ଜୀକରଣ', menu: 'ମେନୁ', navigateTitle: 'ଜଳସହାୟ ନେଭିଗେଟ୍ କରନ୍ତୁ', languageLabel: 'ଭାଷା', chooseLanguage: 'ଭାଷା ବାଛନ୍ତୁ', keyPlatformFeatures: 'ମୁଖ୍ୟ ପ୍ଲାଟଫର୍ମ ବୈଶିଷ୍ଟ୍ୟ', realTimeTracking: 'ରିଅଲ୍-ଟାଇମ୍ ଟ୍ରାକିଂ', proof: 'ଫଟୋ ଓ ଭିଡିଓ ପ୍ରମାଣ', gpsPrecision: 'GPS ସଠିକତା', authorityDashboardFeature: 'କର୍ତ୍ତୃପକ୍ଷ ଡ୍ୟାସବୋର୍ଡ', emergencySosMode: 'ଜରୁରୀ SOS ମୋଡ୍', waterAnalytics: 'ଜଳ ବିଶ୍ଳେଷଣ', howJalSahayWorks: 'ଜଳସହାୟ କିପରି କାମ କରେ', waterConservationNews: 'ଜଳ ସଂରକ୍ଷଣ ଓ ପୌର ସମ୍ବାଦ', articlesGuidelines: 'ସ୍ମାର୍ଟ ଜଳ ପରିଚାଳନା ବିଷୟରେ ଲେଖା ଓ ମାର୍ଗଦର୍ଶିକା।', userProfileSettings: 'ବ୍ୟବହାରକାରୀ ପ୍ରୋଫାଇଲ୍ ସେଟିଂସ୍', registeredWard: 'ପଞ୍ଜୀକୃତ ୱାର୍ଡ', signOut: 'ସାଇନ୍ ଆଉଟ୍', liveComplaintMap: 'ଲାଇଭ୍ ଅଭିଯୋଗ ମାନଚିତ୍ର', useMyGps: 'ମୋ GPS ବ୍ୟବହାର କରନ୍ତୁ' });

const urdu = makeRegionalLanguage({ badge: 'جدید بلدیاتی ٹیکنالوجی', title: 'سمارٹ پانی شکایت انتظامی نظام', reportComplaint: 'شکایت درج کریں', trackComplaint: 'شکایت کا سراغ لگائیں', serviceDesk: 'سروس ڈیسک آن لائن', reportIssue: 'مسئلہ رپورٹ کریں', home: 'ہوم', report: 'شکایت رپورٹ', track: 'حالت دیکھیں', analytics: 'تجزیہ', comparison: 'موازنہ', blog: 'خبریں اور بلاگ', rewards: 'شہری انعامات', operations: 'کارروائیاں', dashboard: 'ڈیش بورڈ', bookService: 'سروس بک کریں', payments: 'ادائیگیاں', profile: 'پروفائل', loginRegister: 'لاگ ان یا رجسٹر', menu: 'مینو', navigateTitle: 'جل سہائے نیویگیٹ کریں', languageLabel: 'زبان', chooseLanguage: 'زبان منتخب کریں', keyPlatformFeatures: 'اہم پلیٹ فارم خصوصیات', realTimeTracking: 'حقیقی وقت کی نگرانی', proof: 'تصویر اور ویڈیو ثبوت', gpsPrecision: 'GPS درستگی', authorityDashboardFeature: 'اختیار ڈیش بورڈ', emergencySosMode: 'ہنگامی SOS موڈ', waterAnalytics: 'پانی کا تجزیہ', howJalSahayWorks: 'جل سہائے کیسے کام کرتا ہے', waterConservationNews: 'پانی کے تحفظ اور بلدیاتی خبریں', articlesGuidelines: 'سمارٹ پانی کے انتظام پر مضامین اور رہنما اصول۔', userProfileSettings: 'صارف پروفائل ترتیبات', registeredWard: 'رجسٹرڈ وارڈ', signOut: 'سائن آؤٹ', liveComplaintMap: 'براہ راست شکایت کا نقشہ', useMyGps: 'میرا GPS استعمال کریں' });

const sanskrit = makeRegionalLanguage({ badge: 'नूतननगरपालिकातन्त्रज्ञानम्', title: 'स्मार्टजलशिकायतप्रबन्धनप्रणाली', reportComplaint: 'शिकायतां पञ्जीकरोतु', trackComplaint: 'शिकायतास्थितिं पश्यतु', serviceDesk: 'सेवाकेन्द्रम् अन्तर्जाले', reportIssue: 'समस्यां निवेदयतु', home: 'गृहम्', report: 'शिकायतानिवेदनम्', track: 'स्थितिं पश्यतु', analytics: 'विश्लेषणम्', comparison: 'तुलना', blog: 'वार्ताः लेखाश्च', rewards: 'नागरिकपुरस्काराः', operations: 'कार्याणि', dashboard: 'पटलम्', bookService: 'सेवां आरक्षतु', payments: 'भुगतानानि', profile: 'परिचयः', loginRegister: 'प्रवेशः पञ्जीकरणं वा', menu: 'सूची', navigateTitle: 'जलसहायं मार्गयतु', languageLabel: 'भाषा', chooseLanguage: 'भाषां चिनोतु', keyPlatformFeatures: 'मञ्चस्य मुख्यविशेषताः', realTimeTracking: 'तत्कालानुवीक्षणम्', proof: 'चित्रचलच्चित्रप्रमाणम्', gpsPrecision: 'GPS शुद्धता', authorityDashboardFeature: 'अधिकारीपटलम्', emergencySosMode: 'आपत्कालीन SOS पद्धतिः', waterAnalytics: 'जलविश्लेषणम्', howJalSahayWorks: 'जलसहायः कथं कार्यं करोति', waterConservationNews: 'जलसंरक्षणनगरपालिकावार्ताः', articlesGuidelines: 'स्मार्टजलप्रबन्धने लेखाः मार्गदर्शिकाश्च।', userProfileSettings: 'उपयोक्तृपरिचयव्यवस्थाः', registeredWard: 'पञ्जीकृतप्रभागः', signOut: 'निर्गमनम्', liveComplaintMap: 'प्रत्यक्षशिकायतामानचित्रम्', useMyGps: 'मम GPS उपयोजयतु' });
const bhojpuri = makeRegionalLanguage({ badge: 'नयका पीढ़ी के नगर तकनीक', title: 'स्मार्ट पानी शिकायत प्रबंधन सिस्टम', reportComplaint: 'शिकायत दर्ज करीं', trackComplaint: 'शिकायत के स्थिति देखीं', serviceDesk: 'सेवा डेस्क ऑनलाइन', reportIssue: 'समस्या बताईं', home: 'घर', report: 'शिकायत रिपोर्ट', track: 'स्थिति ट्रैक करीं', analytics: 'विश्लेषण', comparison: 'तुलना', blog: 'समाचार आ ब्लॉग', rewards: 'नागरिक इनाम', operations: 'कामकाज', dashboard: 'डैशबोर्ड', bookService: 'सेवा बुक करीं', payments: 'भुगतान', profile: 'प्रोफाइल', loginRegister: 'लॉगिन या रजिस्टर', menu: 'मेनू', navigateTitle: 'जलसहाय पर जाईं', languageLabel: 'भाषा', chooseLanguage: 'भाषा चुनीं', keyPlatformFeatures: 'मुख्य प्लेटफॉर्म सुविधा', realTimeTracking: 'तुरंत ट्रैकिंग', proof: 'फोटो आ वीडियो सबूत', gpsPrecision: 'GPS सटीकता', authorityDashboardFeature: 'अधिकारी डैशबोर्ड', emergencySosMode: 'आपात SOS मोड', waterAnalytics: 'पानी विश्लेषण', howJalSahayWorks: 'जलसहाय कइसे काम करेला', waterConservationNews: 'पानी बचाव आ नगर समाचार', articlesGuidelines: 'स्मार्ट पानी प्रबंधन पर लेख आ मार्गदर्शन।', userProfileSettings: 'उपयोगकर्ता प्रोफाइल सेटिंग', registeredWard: 'दर्ज वार्ड', signOut: 'साइन आउट', liveComplaintMap: 'लाइव शिकायत नक्शा', useMyGps: 'हमार GPS इस्तेमाल करीं' });
const maithili = makeRegionalLanguage({ badge: 'नव पीढ़ी के नगर तकनीक', title: 'स्मार्ट जल शिकायत प्रबंधन प्रणाली', reportComplaint: 'शिकायत दर्ज करू', trackComplaint: 'शिकायतक स्थिति देखू', serviceDesk: 'सेवा डेस्क ऑनलाइन', reportIssue: 'समस्या बताउ', home: 'घर', report: 'शिकायत रिपोर्ट', track: 'स्थिति देखू', analytics: 'विश्लेषण', comparison: 'तुलना', blog: 'समाचार आ ब्लॉग', rewards: 'नागरिक पुरस्कार', operations: 'कार्य', dashboard: 'डैशबोर्ड', bookService: 'सेवा बुक करू', payments: 'भुगतान', profile: 'प्रोफाइल', loginRegister: 'लॉगिन अथवा पंजीकरण', menu: 'मेनू', navigateTitle: 'जलसहाय पर जाउ', languageLabel: 'भाषा', chooseLanguage: 'भाषा चुनू', keyPlatformFeatures: 'मुख्य मंचक विशेषता', realTimeTracking: 'तत्काल ट्रैकिंग', proof: 'फोटो आ वीडियो प्रमाण', gpsPrecision: 'GPS सटीकता', authorityDashboardFeature: 'अधिकारी डैशबोर्ड', emergencySosMode: 'आपात SOS मोड', waterAnalytics: 'जल विश्लेषण', howJalSahayWorks: 'जलसहाय कोना काज करैत अछि', waterConservationNews: 'जल संरक्षण आ नगर समाचार', articlesGuidelines: 'स्मार्ट जल प्रबंधन पर लेख आ निर्देश।', userProfileSettings: 'उपयोगकर्ता प्रोफाइल सेटिंग', registeredWard: 'पंजीकृत वार्ड', signOut: 'बाहर निकलू', liveComplaintMap: 'लाइव शिकायत मानचित्र', useMyGps: 'हमर GPS उपयोग करू' });
const chhattisgarhi = makeRegionalLanguage({ badge: 'नवा पीढ़ी के नगर तकनीक', title: 'स्मार्ट पानी शिकायत प्रबंधन सिस्टम', reportComplaint: 'शिकायत दरज करव', trackComplaint: 'शिकायत के स्थिति देखव', serviceDesk: 'सेवा डेस्क ऑनलाइन', reportIssue: 'समस्या बताव', home: 'घर', report: 'शिकायत रिपोर्ट', track: 'स्थिति देखव', analytics: 'विश्लेषण', comparison: 'तुलना', blog: 'समाचार अउ ब्लॉग', rewards: 'नागरिक इनाम', operations: 'कामकाज', dashboard: 'डैशबोर्ड', bookService: 'सेवा बुक करव', payments: 'भुगतान', profile: 'प्रोफाइल', loginRegister: 'लॉगिन या रजिस्टर', menu: 'मेनू', navigateTitle: 'जलसहाय मं जाव', languageLabel: 'भाखा', chooseLanguage: 'भाखा चुनव', keyPlatformFeatures: 'मुख्य प्लेटफार्म सुविधा', realTimeTracking: 'तुरंत ट्रैकिंग', proof: 'फोटो अउ वीडियो सबूत', gpsPrecision: 'GPS सटीकता', authorityDashboardFeature: 'अधिकारी डैशबोर्ड', emergencySosMode: 'आपात SOS मोड', waterAnalytics: 'पानी विश्लेषण', howJalSahayWorks: 'जलसहाय कइसे काम करथे', waterConservationNews: 'पानी बचाव अउ नगर समाचार', articlesGuidelines: 'स्मार्ट पानी प्रबंधन के लेख अउ गाइड।', userProfileSettings: 'उपयोगकर्ता प्रोफाइल सेटिंग', registeredWard: 'दरज वार्ड', signOut: 'बाहर निकलव', liveComplaintMap: 'लाइव शिकायत नक्शा', useMyGps: 'मोर GPS उपयोग करव' });

const sharedRegionalLabels = {
  gu: { activeJobs: 'સક્રિય કામ', assignedTeams: 'નિયુક્ત ટીમો', bookedValue: 'બુક કરેલી કિંમત', requests: 'વિનંતીઓ', incomingServiceRequests: 'આવતી સેવા વિનંતીઓ', noLiveServiceRequests: 'કોઈ સેવા વિનંતી રાહ જોઈ રહી નથી.', priorityAlerts: 'પ્રાથમિકતા ચેતવણીઓ', settlementSummary: 'સમાધાન સારાંશ', customerService: 'ગ્રાહક સેવા', service: 'સેવા', location: 'સ્થાન', status: 'સ્થિતિ', priority: 'પ્રાથમિકતા', address: 'સરનામું', description: 'વર્ણન', loading: 'લોડ થઈ રહ્યું છે' },
  ta: { activeJobs: 'செயலில் உள்ள பணிகள்', assignedTeams: 'ஒதுக்கப்பட்ட குழுக்கள்', bookedValue: 'முன்பதிவு மதிப்பு', requests: 'கோரிக்கைகள்', incomingServiceRequests: 'வரும் சேவை கோரிக்கைகள்', noLiveServiceRequests: 'சேவை கோரிக்கைகள் எதுவும் காத்திருக்கவில்லை.', priorityAlerts: 'முன்னுரிமை எச்சரிக்கைகள்', settlementSummary: 'தீர்வு சுருக்கம்', customerService: 'வாடிக்கையாளர் சேவை', service: 'சேவை', location: 'இடம்', status: 'நிலை', priority: 'முன்னுரிமை', address: 'முகவரி', description: 'விளக்கம்', loading: 'ஏற்றுகிறது' },
  te: { activeJobs: 'క్రియాశీల పనులు', assignedTeams: 'కేటాయించిన బృందాలు', bookedValue: 'బుక్ చేసిన విలువ', requests: 'అభ్యర్థనలు', incomingServiceRequests: 'వస్తున్న సేవా అభ్యర్థనలు', noLiveServiceRequests: 'సేవా అభ్యర్థనలు ఏవీ వేచి లేవు.', priorityAlerts: 'ప్రాధాన్యత హెచ్చరికలు', settlementSummary: 'సెటిల్‌మెంట్ సారాంశం', customerService: 'కస్టమర్ సేవ', service: 'సేవ', location: 'స్థానం', status: 'స్థితి', priority: 'ప్రాధాన్యత', address: 'చిరునామా', description: 'వివరణ', loading: 'లోడ్ అవుతోంది' },
  bn: { activeJobs: 'সক্রিয় কাজ', assignedTeams: 'নিযুক্ত দল', bookedValue: 'বুক করা মূল্য', requests: 'অনুরোধ', incomingServiceRequests: 'আসা পরিষেবা অনুরোধ', noLiveServiceRequests: 'কোনও পরিষেবা অনুরোধ অপেক্ষায় নেই।', priorityAlerts: 'অগ্রাধিকার সতর্কতা', settlementSummary: 'নিষ্পত্তির সারাংশ', customerService: 'গ্রাহক পরিষেবা', service: 'পরিষেবা', location: 'অবস্থান', status: 'অবস্থা', priority: 'অগ্রাধিকার', address: 'ঠিকানা', description: 'বিবরণ', loading: 'লোড হচ্ছে' },
  kn: { activeJobs: 'ಸಕ್ರಿಯ ಕೆಲಸಗಳು', assignedTeams: 'ನಿಯೋಜಿತ ತಂಡಗಳು', bookedValue: 'ಬುಕ್ ಮಾಡಿದ ಮೌಲ್ಯ', requests: 'ವಿನಂತಿಗಳು', incomingServiceRequests: 'ಬರುವ ಸೇವಾ ವಿನಂತಿಗಳು', noLiveServiceRequests: 'ಯಾವುದೇ ಸೇವಾ ವಿನಂತಿಗಳು ಕಾಯುತ್ತಿಲ್ಲ.', priorityAlerts: 'ಆದ್ಯತೆಯ ಎಚ್ಚರಿಕೆಗಳು', settlementSummary: 'ಪಾವತಿ ಸಾರಾಂಶ', customerService: 'ಗ್ರಾಹಕ ಸೇವೆ', service: 'ಸೇವೆ', location: 'ಸ್ಥಳ', status: 'ಸ್ಥಿತಿ', priority: 'ಆದ್ಯತೆ', address: 'ವಿಳಾಸ', description: 'ವಿವರಣೆ', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ' },
  ml: { activeJobs: 'സജീവ ജോലികൾ', assignedTeams: 'നിയോഗിച്ച ടീമുകൾ', bookedValue: 'ബുക്ക് ചെയ്ത മൂല്യം', requests: 'അഭ്യർത്ഥനകൾ', incomingServiceRequests: 'വരുന്ന സേവന അഭ്യർത്ഥനകൾ', noLiveServiceRequests: 'സേവന അഭ്യർത്ഥനകളൊന്നും കാത്തിരിക്കുന്നില്ല.', priorityAlerts: 'മുൻഗണനാ അറിയിപ്പുകൾ', settlementSummary: 'സെറ്റിൽമെന്റ് സംഗ്രഹം', customerService: 'ഉപഭോക്തൃ സേവനം', service: 'സേവനം', location: 'സ്ഥലം', status: 'നില', priority: 'മുൻഗണന', address: 'വിലാസം', description: 'വിവരണം', loading: 'ലോഡ് ചെയ്യുന്നു' },
  pa: { activeJobs: 'ਸਰਗਰਮ ਕੰਮ', assignedTeams: 'ਨਿਯੁਕਤ ਟੀਮਾਂ', bookedValue: 'ਬੁੱਕ ਕੀਤੀ ਕੀਮਤ', requests: 'ਬੇਨਤੀਆਂ', incomingServiceRequests: 'ਆ ਰਹੀਆਂ ਸੇਵਾ ਬੇਨਤੀਆਂ', noLiveServiceRequests: 'ਕੋਈ ਸੇਵਾ ਬੇਨਤੀ ਉਡੀਕ ਵਿੱਚ ਨਹੀਂ ਹੈ।', priorityAlerts: 'ਤਰਜੀਹ ਚੇਤਾਵਨੀਆਂ', settlementSummary: 'ਨਿਪਟਾਰਾ ਸਾਰ', customerService: 'ਗਾਹਕ ਸੇਵਾ', service: 'ਸੇਵਾ', location: 'ਸਥਾਨ', status: 'ਸਥਿਤੀ', priority: 'ਤਰਜੀਹ', address: 'ਪਤਾ', description: 'ਵੇਰਵਾ', loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ' },
  or: { activeJobs: 'ସକ୍ରିୟ କାର୍ଯ୍ୟ', assignedTeams: 'ନିଯୁକ୍ତ ଦଳ', bookedValue: 'ବୁକ୍ ମୂଲ୍ୟ', requests: 'ଅନୁରୋଧ', incomingServiceRequests: 'ଆସୁଥିବା ସେବା ଅନୁରୋଧ', noLiveServiceRequests: 'କୌଣସି ସେବା ଅନୁରୋଧ ଅପେକ୍ଷାରେ ନାହିଁ।', priorityAlerts: 'ପ୍ରାଥମିକତା ସତର୍କତା', settlementSummary: 'ନିଷ୍ପତ୍ତି ସାରାଂଶ', customerService: 'ଗ୍ରାହକ ସେବା', service: 'ସେବା', location: 'ସ୍ଥାନ', status: 'ସ୍ଥିତି', priority: 'ପ୍ରାଥମିକତା', address: 'ଠିକଣା', description: 'ବର୍ଣ୍ଣନା', loading: 'ଲୋଡ୍ ହେଉଛି' },
  ur: { activeJobs: 'فعال کام', assignedTeams: 'مقرر ٹیمیں', bookedValue: 'بک شدہ رقم', requests: 'درخواستیں', incomingServiceRequests: 'آنے والی سروس درخواستیں', noLiveServiceRequests: 'کوئی سروس درخواست زیر انتظار نہیں۔', priorityAlerts: 'ترجیحی انتباہات', settlementSummary: 'تصفیہ کا خلاصہ', customerService: 'صارف سروس', service: 'سروس', location: 'مقام', status: 'حالت', priority: 'ترجیح', address: 'پتہ', description: 'تفصیل', loading: 'لوڈ ہو رہا ہے' },
  bho: { activeJobs: 'चालू काम', assignedTeams: 'लगावल टीम', bookedValue: 'बुक भइल कीमत', requests: 'निवेदन', incomingServiceRequests: 'आवत सेवा निवेदन', noLiveServiceRequests: 'कवनो सेवा निवेदन इंतजार में नइखे.', priorityAlerts: 'जरूरी चेतावनी', settlementSummary: 'निपटारा सार', customerService: 'ग्राहक सेवा', service: 'सेवा', location: 'जगह', status: 'स्थिति', priority: 'जरूरत', address: 'पता', description: 'ब्यौरा', loading: 'लोड हो रहल बा' },
  mai: { activeJobs: 'सक्रिय काज', assignedTeams: 'नियुक्त दल', bookedValue: 'बुक मूल्य', requests: 'अनुरोध', incomingServiceRequests: 'आबि रहल सेवा अनुरोध', noLiveServiceRequests: 'कोनो सेवा अनुरोध प्रतीक्षा मे नहि अछि।', priorityAlerts: 'प्राथमिकता सूचना', settlementSummary: 'निपटारा सार', customerService: 'ग्राहक सेवा', service: 'सेवा', location: 'स्थान', status: 'स्थिति', priority: 'प्राथमिकता', address: 'पता', description: 'विवरण', loading: 'लोड भ रहल अछि' },
  chh: { activeJobs: 'चलत काम', assignedTeams: 'लगाय गे टीम', bookedValue: 'बुक कीमत', requests: 'निवेदन', incomingServiceRequests: 'आवत सेवा निवेदन', noLiveServiceRequests: 'कऊनो सेवा निवेदन अगोरत नइ हे.', priorityAlerts: 'जरूरी चेतावनी', settlementSummary: 'निपटारा सार', customerService: 'ग्राहक सेवा', service: 'सेवा', location: 'जगह', status: 'स्थिति', priority: 'जरूरत', address: 'पता', description: 'ब्यौरा', loading: 'लोड होवत हे' },
  sa: { activeJobs: 'सक्रियकार्याणि', assignedTeams: 'नियुक्तदलानि', bookedValue: 'आरक्षितमूल्यम्', requests: 'अनुरोधाः', incomingServiceRequests: 'आगच्छन्तःसेवानुरोधाः', noLiveServiceRequests: 'सेवानुरोधाः प्रतीक्षायां न सन्ति।', priorityAlerts: 'प्राथमिकतासूचनाः', settlementSummary: 'निपटारसारांशः', customerService: 'ग्राहकसेवा', service: 'सेवा', location: 'स्थानम्', status: 'स्थितिः', priority: 'प्राथमिकता', address: 'पता', description: 'विवरणम्', loading: 'लोड् भवति' }
};

const flowLabels = {
  gu: { reportWaterComplaint: 'પાણીની ફરિયાદ નોંધાવો', fillAccurateDetails: 'ઝડપી નગરપાલિકા કાર્યવાહી માટે સાચી વિગતો ભરો.', trackComplaintStatus: 'ફરિયાદની સ્થિતિ ટ્રૅક કરો', complaintIdPhone: 'ફરિયાદ ID અથવા નોંધાયેલ ફોન નંબર દાખલ કરો', search: 'શોધો', noComplaintRecords: 'કોઈ ફરિયાદ રેકોર્ડ મળ્યો નથી.', civicRewards: 'નાગરિક પુરસ્કારો', rewardingParticipation: 'જળ નેટવર્કમાં ચકાસાયેલ ભાગીદારી માટે પુરસ્કાર', comparisonDescription: 'સેવા કામગીરીની સરખામણી કરો', traditionalVsJalSahay: 'પરંપરાગત સિસ્ટમ વિરુદ્ધ જલસહાય', whyModernCities: 'આધુનિક શહેરો સ્વચાલિત પાણી વ્યવસ્થાપન કેમ અપનાવે છે.', feature: 'સુવિધા', traditionalSystem: 'પરંપરાગત સિસ્ટમ', jalsahaySmartSystem: 'જલસહાય સ્માર્ટ સિસ્ટમ', authorityPortal: 'સત્તાધિકારી પોર્ટલ', operationsDashboard: 'કામગીરી ડેશબોર્ડ' },
  ta: { reportWaterComplaint: 'நீர் புகாரைப் பதிவு செய்க', fillAccurateDetails: 'விரைவான நகராட்சி நடவடிக்கைக்கு சரியான விவரங்களை நிரப்பவும்.', trackComplaintStatus: 'புகார் நிலையைத் தொடர்க', complaintIdPhone: 'புகார் ID அல்லது பதிவு செய்த தொலைபேசி எண்ணை உள்ளிடவும்', search: 'தேடு', noComplaintRecords: 'புகார் பதிவுகள் எதுவும் இல்லை.', civicRewards: 'குடிமக்கள் வெகுமதிகள்', rewardingParticipation: 'நீர் வலையமைப்பில் சரிபார்க்கப்பட்ட பங்கேற்புக்கான வெகுமதி', comparisonDescription: 'சேவை செயல்திறனை ஒப்பிடுக', traditionalVsJalSahay: 'பாரம்பரிய அமைப்பு மற்றும் ஜலசஹாய்', whyModernCities: 'நவீன நகரங்கள் தானியங்கி நீர் மேலாண்மையை ஏன் ஏற்கின்றன.', feature: 'அம்சம்', traditionalSystem: 'பாரம்பரிய அமைப்பு', jalsahaySmartSystem: 'ஜலசஹாய் ஸ்மார்ட் அமைப்பு', authorityPortal: 'அதிகாரி தளம்', operationsDashboard: 'செயல்பாட்டு டாஷ்போர்டு' },
  te: { reportWaterComplaint: 'నీటి ఫిర్యాదు నమోదు చేయండి', fillAccurateDetails: 'త్వరిత మునిసిపల్ చర్య కోసం సరైన వివరాలు నమోదు చేయండి.', trackComplaintStatus: 'ఫిర్యాదు స్థితిని ట్రాక్ చేయండి', complaintIdPhone: 'ఫిర్యాదు ID లేదా నమోదైన ఫోన్ నంబర్ నమోదు చేయండి', search: 'వెతకండి', noComplaintRecords: 'ఫిర్యాదు రికార్డులు లేవు.', civicRewards: 'పౌర బహుమతులు', rewardingParticipation: 'నీటి నెట్‌వర్క్‌లో ధృవీకరించిన భాగస్వామ్యానికి బహుమతి', comparisonDescription: 'సేవ పనితీరును పోల్చండి', traditionalVsJalSahay: 'సాంప్రదాయ వ్యవస్థ మరియు జలసహాయ్', whyModernCities: 'ఆధునిక నగరాలు ఆటోమేటెడ్ నీటి నిర్వహణను ఎందుకు ఎంచుకుంటున్నాయి.', feature: 'లక్షణం', traditionalSystem: 'సాంప్రదాయ వ్యవస్థ', jalsahaySmartSystem: 'జలసహాయ్ స్మార్ట్ వ్యవస్థ', authorityPortal: 'అధికార పోర్టల్', operationsDashboard: 'కార్యకలాపాల డాష్‌బోర్డ్' },
  bn: { reportWaterComplaint: 'জল অভিযোগ জানান', fillAccurateDetails: 'দ্রুত পৌরসভার পদক্ষেপের জন্য সঠিক তথ্য দিন।', trackComplaintStatus: 'অভিযোগের অবস্থা অনুসরণ করুন', complaintIdPhone: 'অভিযোগ ID বা নিবন্ধিত ফোন নম্বর লিখুন', search: 'অনুসন্ধান', noComplaintRecords: 'কোনও অভিযোগের রেকর্ড পাওয়া যায়নি।', civicRewards: 'নাগরিক পুরস্কার', rewardingParticipation: 'জল নেটওয়ার্কে যাচাইকৃত অংশগ্রহণের পুরস্কার', comparisonDescription: 'পরিষেবার কার্যক্ষমতা তুলনা করুন', traditionalVsJalSahay: 'প্রথাগত ব্যবস্থা বনাম জলসহায়', whyModernCities: 'আধুনিক শহরগুলি কেন স্বয়ংক্রিয় জল ব্যবস্থাপনা গ্রহণ করছে।', feature: 'বৈশিষ্ট্য', traditionalSystem: 'প্রথাগত ব্যবস্থা', jalsahaySmartSystem: 'জলসহায় স্মার্ট ব্যবস্থা', authorityPortal: 'কর্তৃপক্ষ পোর্টাল', operationsDashboard: 'কার্যক্রম ড্যাশবোর্ড' },
  kn: { reportWaterComplaint: 'ನೀರಿನ ದೂರು ದಾಖಲಿಸಿ', fillAccurateDetails: 'ತ್ವರಿತ ನಗರಸಭೆ ಕ್ರಮಕ್ಕಾಗಿ ಸರಿಯಾದ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.', trackComplaintStatus: 'ದೂರು ಸ್ಥಿತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ', complaintIdPhone: 'ದೂರು ID ಅಥವಾ ನೋಂದಾಯಿತ ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ', search: 'ಹುಡುಕಿ', noComplaintRecords: 'ಯಾವುದೇ ದೂರು ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.', civicRewards: 'ನಾಗರಿಕ ಬಹುಮಾನಗಳು', rewardingParticipation: 'ನೀರಿನ ಜಾಲದಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ಭಾಗವಹಿಸುವಿಕೆಗೆ ಬಹುಮಾನ', comparisonDescription: 'ಸೇವಾ ಕಾರ್ಯಕ್ಷಮತೆಯನ್ನು ಹೋಲಿಸಿ', traditionalVsJalSahay: 'ಸಾಂಪ್ರದಾಯಿಕ ವ್ಯವಸ್ಥೆ ಮತ್ತು ಜಲಸಹಾಯ್', whyModernCities: 'ಆಧುನಿಕ ನಗರಗಳು ಸ್ವಯಂಚಾಲಿತ ನೀರು ನಿರ್ವಹಣೆಯನ್ನು ಏಕೆ ಅಳವಡಿಸಿಕೊಳ್ಳುತ್ತಿವೆ.', feature: 'ವೈಶಿಷ್ಟ್ಯ', traditionalSystem: 'ಸಾಂಪ್ರದಾಯಿಕ ವ್ಯವಸ್ಥೆ', jalsahaySmartSystem: 'ಜಲಸಹಾಯ್ ಸ್ಮಾರ್ಟ್ ವ್ಯವಸ್ಥೆ', authorityPortal: 'ಅಧಿಕಾರಿ ಪೋರ್ಟಲ್', operationsDashboard: 'ಕಾರ್ಯಾಚರಣೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್' },
  ml: { reportWaterComplaint: 'ജല പരാതി നൽകുക', fillAccurateDetails: 'വേഗത്തിലുള്ള നഗരസഭാ നടപടിക്കായി കൃത്യമായ വിവരങ്ങൾ നൽകുക.', trackComplaintStatus: 'പരാതിയുടെ നില പിന്തുടരുക', complaintIdPhone: 'പരാതി ID അല്ലെങ്കിൽ രജിസ്റ്റർ ചെയ്ത ഫോൺ നമ്പർ നൽകുക', search: 'തിരയുക', noComplaintRecords: 'പരാതി രേഖകളൊന്നും കണ്ടെത്തിയില്ല.', civicRewards: 'പൗര സമ്മാനങ്ങൾ', rewardingParticipation: 'ജല ശൃംഖലയിലെ സ്ഥിരീകരിച്ച പങ്കാളിത്തത്തിനുള്ള സമ്മാനം', comparisonDescription: 'സേവന പ്രകടനം താരതമ്യം ചെയ്യുക', traditionalVsJalSahay: 'പരമ്പരാഗത സംവിധാനം വേഴ്സസ് ജൽസഹായ്', whyModernCities: 'ആധുനിക നഗരങ്ങൾ ഓട്ടോമേറ്റഡ് ജല മാനേജ്മെന്റ് സ്വീകരിക്കുന്നത് എന്തുകൊണ്ട്.', feature: 'സവിശേഷത', traditionalSystem: 'പരമ്പരാഗത സംവിധാനം', jalsahaySmartSystem: 'ജൽസഹായ് സ്മാർട്ട് സംവിധാനം', authorityPortal: 'അധികാരി പോർട്ടൽ', operationsDashboard: 'പ്രവർത്തന ഡാഷ്ബോർഡ്' },
  pa: { reportWaterComplaint: 'ਪਾਣੀ ਦੀ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ', fillAccurateDetails: 'ਤੇਜ਼ ਨਗਰਪਾਲਿਕਾ ਕਾਰਵਾਈ ਲਈ ਸਹੀ ਵੇਰਵੇ ਭਰੋ।', trackComplaintStatus: 'ਸ਼ਿਕਾਇਤ ਦੀ ਸਥਿਤੀ ਟਰੈਕ ਕਰੋ', complaintIdPhone: 'ਸ਼ਿਕਾਇਤ ID ਜਾਂ ਰਜਿਸਟਰਡ ਫੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ', search: 'ਖੋਜੋ', noComplaintRecords: 'ਕੋਈ ਸ਼ਿਕਾਇਤ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।', civicRewards: 'ਨਾਗਰਿਕ ਇਨਾਮ', rewardingParticipation: 'ਪਾਣੀ ਨੈੱਟਵਰਕ ਵਿੱਚ ਪ੍ਰਮਾਣਿਤ ਭਾਗੀਦਾਰੀ ਲਈ ਇਨਾਮ', comparisonDescription: 'ਸੇਵਾ ਪ੍ਰਦਰਸ਼ਨ ਦੀ ਤੁਲਨਾ ਕਰੋ', traditionalVsJalSahay: 'ਰਵਾਇਤੀ ਪ੍ਰਣਾਲੀ ਬਨਾਮ ਜਲਸਹਾਇ', whyModernCities: 'ਆਧੁਨਿਕ ਸ਼ਹਿਰ ਸਵੈਚਾਲਿਤ ਪਾਣੀ ਪ੍ਰਬੰਧਨ ਕਿਉਂ ਅਪਣਾ ਰਹੇ ਹਨ।', feature: 'ਵਿਸ਼ੇਸ਼ਤਾ', traditionalSystem: 'ਰਵਾਇਤੀ ਪ੍ਰਣਾਲੀ', jalsahaySmartSystem: 'ਜਲਸਹਾਇ ਸਮਾਰਟ ਪ੍ਰਣਾਲੀ', authorityPortal: 'ਅਧਿਕਾਰੀ ਪੋਰਟਲ', operationsDashboard: 'ਕਾਰਵਾਈ ਡੈਸ਼ਬੋਰਡ' },
  or: { reportWaterComplaint: 'ଜଳ ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ', fillAccurateDetails: 'ତୁରନ୍ତ ପୌର କାର୍ଯ୍ୟାନୁଷ୍ଠାନ ପାଇଁ ସଠିକ ବିବରଣୀ ଦିଅନ୍ତୁ।', trackComplaintStatus: 'ଅଭିଯୋଗ ସ୍ଥିତି ଟ୍ରାକ୍ କରନ୍ତୁ', complaintIdPhone: 'ଅଭିଯୋଗ ID କିମ୍ବା ପଞ୍ଜୀକୃତ ଫୋନ୍ ନମ୍ବର ଦିଅନ୍ତୁ', search: 'ଖୋଜନ୍ତୁ', noComplaintRecords: 'କୌଣସି ଅଭିଯୋଗ ରେକର୍ଡ ମିଳିଲା ନାହିଁ।', civicRewards: 'ନାଗରିକ ପୁରସ୍କାର', rewardingParticipation: 'ଜଳ ନେଟୱର୍କରେ ଯାଞ୍ଚିତ ଅଂଶଗ୍ରହଣ ପାଇଁ ପୁରସ୍କାର', comparisonDescription: 'ସେବା ପ୍ରଦର୍ଶନ ତୁଳନା କରନ୍ତୁ', traditionalVsJalSahay: 'ପାରମ୍ପରିକ ବ୍ୟବସ୍ଥା ବନାମ ଜଳସହାୟ', whyModernCities: 'ଆଧୁନିକ ସହରଗୁଡ଼ିକ ସ୍ୱୟଂଚାଳିତ ଜଳ ପରିଚାଳନା କାହିଁକି ଗ୍ରହଣ କରୁଛନ୍ତି।', feature: 'ବୈଶିଷ୍ଟ୍ୟ', traditionalSystem: 'ପାରମ୍ପରିକ ବ୍ୟବସ୍ଥା', jalsahaySmartSystem: 'ଜଳସହାୟ ସ୍ମାର୍ଟ ବ୍ୟବସ୍ଥା', authorityPortal: 'କର୍ତ୍ତୃପକ୍ଷ ପୋର୍ଟାଲ୍', operationsDashboard: 'କାର୍ଯ୍ୟ ଡ୍ୟାସବୋର୍ଡ' },
  ur: { reportWaterComplaint: 'پانی کی شکایت درج کریں', fillAccurateDetails: 'فوری بلدیاتی کارروائی کے لیے درست تفصیلات بھریں۔', trackComplaintStatus: 'شکایت کی حالت دیکھیں', complaintIdPhone: 'شکایت ID یا رجسٹرڈ فون نمبر درج کریں', search: 'تلاش', noComplaintRecords: 'شکایت کا کوئی ریکارڈ نہیں ملا۔', civicRewards: 'شہری انعامات', rewardingParticipation: 'پانی کے نیٹ ورک میں تصدیق شدہ شرکت کا انعام', comparisonDescription: 'سروس کی کارکردگی کا موازنہ کریں', traditionalVsJalSahay: 'روایتی نظام بمقابلہ جل سہائے', whyModernCities: 'جدید شہر خودکار پانی کا انتظام کیوں اپنا رہے ہیں۔', feature: 'خصوصیت', traditionalSystem: 'روایتی نظام', jalsahaySmartSystem: 'جل سہائے اسمارٹ نظام', authorityPortal: 'اختیاری پورٹل', operationsDashboard: 'کارروائی ڈیش بورڈ' },
  bho: { reportWaterComplaint: 'पानी के शिकायत दर्ज करीं', fillAccurateDetails: 'जल्दी नगरपालिका काम खातिर सही जानकारी भरीं.', trackComplaintStatus: 'शिकायत के स्थिति देखीं', complaintIdPhone: 'शिकायत ID या रजिस्टर्ड फोन नंबर डालीं', search: 'खोजीं', noComplaintRecords: 'कवनो शिकायत रिकॉर्ड ना मिलल.', civicRewards: 'नागरिक इनाम', rewardingParticipation: 'पानी नेटवर्क में जांचल भागीदारी खातिर इनाम', comparisonDescription: 'सेवा के कामकाज के तुलना करीं', traditionalVsJalSahay: 'पुरान सिस्टम बनाम जलसहाय', whyModernCities: 'आधुनिक शहर स्वचालित पानी प्रबंधन काहे अपना रहल बा.', feature: 'सुविधा', traditionalSystem: 'पुरान सिस्टम', jalsahaySmartSystem: 'जलसहाय स्मार्ट सिस्टम', authorityPortal: 'अधिकारी पोर्टल', operationsDashboard: 'कामकाज डैशबोर्ड' },
  mai: { reportWaterComplaint: 'जल शिकायत दर्ज करू', fillAccurateDetails: 'शीघ्र नगरपालिका कार्रवाई लेल सही विवरण भरू।', trackComplaintStatus: 'शिकायतक स्थिति देखू', complaintIdPhone: 'शिकायत ID अथवा पंजीकृत फोन नंबर भरू', search: 'खोजू', noComplaintRecords: 'कोनो शिकायत रिकॉर्ड नहि भेटल।', civicRewards: 'नागरिक पुरस्कार', rewardingParticipation: 'जल नेटवर्क मे सत्यापित भागीदारी लेल पुरस्कार', comparisonDescription: 'सेवा प्रदर्शनक तुलना करू', traditionalVsJalSahay: 'पारंपरिक प्रणाली बनाम जलसहाय', whyModernCities: 'आधुनिक नगर स्वचालित जल प्रबंधन किएक अपना रहल अछि।', feature: 'विशेषता', traditionalSystem: 'पारंपरिक प्रणाली', jalsahaySmartSystem: 'जलसहाय स्मार्ट प्रणाली', authorityPortal: 'अधिकारी पोर्टल', operationsDashboard: 'कार्य डैशबोर्ड' },
  chh: { reportWaterComplaint: 'पानी के शिकायत दरज करव', fillAccurateDetails: 'जल्दी नगरपालिका काम बर सही जानकारी भरव.', trackComplaintStatus: 'शिकायत के स्थिति देखव', complaintIdPhone: 'शिकायत ID या दरज फोन नंबर डारव', search: 'खोजव', noComplaintRecords: 'कऊनो शिकायत रिकॉर्ड नइ मिलिस.', civicRewards: 'नागरिक इनाम', rewardingParticipation: 'पानी नेटवर्क मं जांचे गे भागीदारी बर इनाम', comparisonDescription: 'सेवा काम के तुलना करव', traditionalVsJalSahay: 'परंपरागत सिस्टम बनाम जलसहाय', whyModernCities: 'आधुनिक सहर स्वचालित पानी प्रबंधन काबर अपनावत हें.', feature: 'सुविधा', traditionalSystem: 'परंपरागत सिस्टम', jalsahaySmartSystem: 'जलसहाय स्मार्ट सिस्टम', authorityPortal: 'अधिकारी पोर्टल', operationsDashboard: 'कामकाज डैशबोर्ड' },
  sa: { reportWaterComplaint: 'जलशिकायतां पञ्जीकरोतु', fillAccurateDetails: 'शीघ्रनगरपालिकाकार्यार्थं यथार्थविवरणं पूरयतु।', trackComplaintStatus: 'शिकायतास्थितिं अनुगच्छतु', complaintIdPhone: 'शिकायतासङ्ख्यां पञ्जीकृतदूरवाणीसङ्ख्यां वा लिखतु', search: 'अन्वेषणम्', noComplaintRecords: 'शिकायतालेखाः न प्राप्ताः।', civicRewards: 'नागरिकपुरस्काराः', rewardingParticipation: 'जलजाले सत्यापितसहभागितायै पुरस्कारः', comparisonDescription: 'सेवाकार्यक्षमतां तुलयतु', traditionalVsJalSahay: 'परम्परागतप्रणाली विरुद्धं जलसहायः', whyModernCities: 'आधुनिकनगराणि स्वचालितजलप्रबन्धनं किमर्थं स्वीकुर्वन्ति।', feature: 'विशेषता', traditionalSystem: 'परम्परागतप्रणाली', jalsahaySmartSystem: 'जलसहायस्मार्टप्रणाली', authorityPortal: 'अधिकारीपटलम्', operationsDashboard: 'कार्यपटलम्' }
};

const translations = { en: baseEnglish, hi: hindi, mr: marathi, gu: { ...gujarati, ...sharedRegionalLabels.gu, ...flowLabels.gu }, ta: { ...tamil, ...sharedRegionalLabels.ta, ...flowLabels.ta }, te: { ...telugu, ...sharedRegionalLabels.te, ...flowLabels.te }, bn: { ...bengali, ...sharedRegionalLabels.bn, ...flowLabels.bn }, kn: { ...kannada, ...sharedRegionalLabels.kn, ...flowLabels.kn }, ml: { ...malayalam, ...sharedRegionalLabels.ml, ...flowLabels.ml }, pa: { ...punjabi, ...sharedRegionalLabels.pa, ...flowLabels.pa }, or: { ...odia, ...sharedRegionalLabels.or, ...flowLabels.or }, ur: { ...urdu, ...sharedRegionalLabels.ur, ...flowLabels.ur }, bho: { ...bhojpuri, ...sharedRegionalLabels.bho, ...flowLabels.bho }, mai: { ...maithili, ...sharedRegionalLabels.mai, ...flowLabels.mai }, chh: { ...chhattisgarhi, ...sharedRegionalLabels.chh, ...flowLabels.chh }, sa: { ...sanskrit, ...sharedRegionalLabels.sa, ...flowLabels.sa } };

const getInitialLanguage = () => {
  const saved = typeof window !== 'undefined' ? window.localStorage.getItem('jalsahay-language') : null;
  if (saved && supportedLanguages.some(lang => lang.code === saved)) {
    return saved;
  }
  return 'en';
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('jalsahay-language', language);
    }
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    languages: supportedLanguages,
    t: translations[language] || translations.en
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
